// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accomodations.commands.sql

package v1

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"go.ssnk.in/inflict/internal/domain"
)

const createAccomodation = `-- name: CreateAccomodation :one
INSERT INTO Accomodations (
    id, member_id, type, address, cost_id
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, member_id, type, address, cost_id, deleted, created_at, updated_at
`

type CreateAccomodationParams struct {
	ID       uuid.UUID               `db:"id" json:"id"`
	MemberID uuid.UUID               `db:"member_id" json:"memberId"`
	Type     domain.AccomodationType `db:"type" json:"type"`
	Address  pgtype.Text             `db:"address" json:"address"`
	CostID   uuid.UUID               `db:"cost_id" json:"costId"`
}

// CreateAccomodation
//
//	INSERT INTO Accomodations (
//	    id, member_id, type, address, cost_id
//	) VALUES (
//	    $1, $2, $3, $4, $5
//	) RETURNING id, member_id, type, address, cost_id, deleted, created_at, updated_at
func (q *Queries) CreateAccomodation(ctx context.Context, arg *CreateAccomodationParams) (*Accomodations, error) {
	row := q.db.QueryRow(ctx, createAccomodation,
		arg.ID,
		arg.MemberID,
		arg.Type,
		arg.Address,
		arg.CostID,
	)
	var i Accomodations
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Type,
		&i.Address,
		&i.CostID,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteAccomodation = `-- name: DeleteAccomodation :exec
UPDATE Accomodations
SET deleted = TRUE, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

// DeleteAccomodation
//
//	UPDATE Accomodations
//	SET deleted = TRUE, updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1
func (q *Queries) DeleteAccomodation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccomodation, id)
	return err
}

const updateAccomodation = `-- name: UpdateAccomodation :one
UPDATE Accomodations
SET
    type = COALESCE($1, type),
    address = COALESCE($2, address),
    cost_id = COALESCE($3, cost_id),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $4
RETURNING id, member_id, type, address, cost_id, deleted, created_at, updated_at
`

type UpdateAccomodationParams struct {
	Type    NullAccomodationType `db:"type" json:"type"`
	Address pgtype.Text          `db:"address" json:"address"`
	CostID  uuid.UUID            `db:"cost_id" json:"costId"`
	ID      uuid.UUID            `db:"id" json:"id"`
}

// UpdateAccomodation
//
//	UPDATE Accomodations
//	SET
//	    type = COALESCE($1, type),
//	    address = COALESCE($2, address),
//	    cost_id = COALESCE($3, cost_id),
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $4
//	RETURNING id, member_id, type, address, cost_id, deleted, created_at, updated_at
func (q *Queries) UpdateAccomodation(ctx context.Context, arg *UpdateAccomodationParams) (*Accomodations, error) {
	row := q.db.QueryRow(ctx, updateAccomodation,
		arg.Type,
		arg.Address,
		arg.CostID,
		arg.ID,
	)
	var i Accomodations
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Type,
		&i.Address,
		&i.CostID,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
