// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accomodations.queries.sql

package v1

import (
	"context"

	"github.com/google/uuid"
)

const listAccomodations = `-- name: ListAccomodations :many
SELECT id, member_id, type, address, cost_id, deleted, created_at, updated_at FROM Accomodations
WHERE member_id = $1 AND deleted = FALSE
`

// ListAccomodations
//
//	SELECT id, member_id, type, address, cost_id, deleted, created_at, updated_at FROM Accomodations
//	WHERE member_id = $1 AND deleted = FALSE
func (q *Queries) ListAccomodations(ctx context.Context, memberID uuid.UUID) ([]*Accomodations, error) {
	rows, err := q.db.Query(ctx, listAccomodations, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Accomodations{}
	for rows.Next() {
		var i Accomodations
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Type,
			&i.Address,
			&i.CostID,
			&i.Deleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
