// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: amounts.commands.sql

package v1

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"go.ssnk.in/inflict/internal/domain"
)

const createAmount = `-- name: CreateAmount :one
INSERT INTO Amounts (id, type, name, sender, receiver, value, currency)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, type, name, sender, receiver, value, currency, deleted, created_at, updated_at
`

type CreateAmountParams struct {
	ID       uuid.UUID         `db:"id" json:"id"`
	Type     domain.AmountType `db:"type" json:"type"`
	Name     string            `db:"name" json:"name"`
	Sender   string            `db:"sender" json:"sender"`
	Receiver string            `db:"receiver" json:"receiver"`
	Value    pgtype.Numeric    `db:"value" json:"value"`
	Currency string            `db:"currency" json:"currency"`
}

// Amount CRUD
//
//	INSERT INTO Amounts (id, type, name, sender, receiver, value, currency)
//	VALUES ($1, $2, $3, $4, $5, $6, $7)
//	RETURNING id, type, name, sender, receiver, value, currency, deleted, created_at, updated_at
func (q *Queries) CreateAmount(ctx context.Context, arg *CreateAmountParams) (*Amounts, error) {
	row := q.db.QueryRow(ctx, createAmount,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.Sender,
		arg.Receiver,
		arg.Value,
		arg.Currency,
	)
	var i Amounts
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Sender,
		&i.Receiver,
		&i.Value,
		&i.Currency,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteAmount = `-- name: DeleteAmount :exec
UPDATE Amounts
SET deleted = TRUE, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

// DeleteAmount
//
//	UPDATE Amounts
//	SET deleted = TRUE, updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1
func (q *Queries) DeleteAmount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAmount, id)
	return err
}

const updateAmount = `-- name: UpdateAmount :one
UPDATE Amounts
SET type = $2,
    name = $3,
    sender = $4,
    receiver = $5,
    value = $6,
    currency = $7,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted = FALSE
RETURNING id, type, name, sender, receiver, value, currency, deleted, created_at, updated_at
`

type UpdateAmountParams struct {
	ID       uuid.UUID         `db:"id" json:"id"`
	Type     domain.AmountType `db:"type" json:"type"`
	Name     string            `db:"name" json:"name"`
	Sender   string            `db:"sender" json:"sender"`
	Receiver string            `db:"receiver" json:"receiver"`
	Value    pgtype.Numeric    `db:"value" json:"value"`
	Currency string            `db:"currency" json:"currency"`
}

// UpdateAmount
//
//	UPDATE Amounts
//	SET type = $2,
//	    name = $3,
//	    sender = $4,
//	    receiver = $5,
//	    value = $6,
//	    currency = $7,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1 AND deleted = FALSE
//	RETURNING id, type, name, sender, receiver, value, currency, deleted, created_at, updated_at
func (q *Queries) UpdateAmount(ctx context.Context, arg *UpdateAmountParams) (*Amounts, error) {
	row := q.db.QueryRow(ctx, updateAmount,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.Sender,
		arg.Receiver,
		arg.Value,
		arg.Currency,
	)
	var i Amounts
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Sender,
		&i.Receiver,
		&i.Value,
		&i.Currency,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
