// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: amounts.queries.sql

package v1

import (
	"context"

	"github.com/google/uuid"
)

const getAmount = `-- name: GetAmount :one
SELECT id, type, name, sender, receiver, value, currency, deleted, created_at, updated_at FROM Amounts
WHERE id = $1 AND deleted = FALSE
`

// Amount Read
//
//	SELECT id, type, name, sender, receiver, value, currency, deleted, created_at, updated_at FROM Amounts
//	WHERE id = $1 AND deleted = FALSE
func (q *Queries) GetAmount(ctx context.Context, id uuid.UUID) (*Amounts, error) {
	row := q.db.QueryRow(ctx, getAmount, id)
	var i Amounts
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Sender,
		&i.Receiver,
		&i.Value,
		&i.Currency,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAmounts = `-- name: ListAmounts :many
SELECT id, type, name, sender, receiver, value, currency, deleted, created_at, updated_at FROM Amounts
WHERE deleted = FALSE
ORDER BY created_at DESC
`

// ListAmounts
//
//	SELECT id, type, name, sender, receiver, value, currency, deleted, created_at, updated_at FROM Amounts
//	WHERE deleted = FALSE
//	ORDER BY created_at DESC
func (q *Queries) ListAmounts(ctx context.Context) ([]*Amounts, error) {
	rows, err := q.db.Query(ctx, listAmounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Amounts{}
	for rows.Next() {
		var i Amounts
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Sender,
			&i.Receiver,
			&i.Value,
			&i.Currency,
			&i.Deleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
