// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maintainances.commands.sql

package v1

import (
	"context"

	"github.com/google/uuid"
)

const createMaintainance = `-- name: CreateMaintainance :one
INSERT INTO Maintainances (id, wealth_id, type, name, cost_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, wealth_id, type, name, cost_id, deleted, created_at, updated_at
`

type CreateMaintainanceParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	WealthID uuid.UUID `db:"wealth_id" json:"wealthId"`
	Type     string    `db:"type" json:"type"`
	Name     string    `db:"name" json:"name"`
	CostID   uuid.UUID `db:"cost_id" json:"costId"`
}

// Maintainance CRUD
//
//	INSERT INTO Maintainances (id, wealth_id, type, name, cost_id)
//	VALUES ($1, $2, $3, $4, $5)
//	RETURNING id, wealth_id, type, name, cost_id, deleted, created_at, updated_at
func (q *Queries) CreateMaintainance(ctx context.Context, arg *CreateMaintainanceParams) (*Maintainances, error) {
	row := q.db.QueryRow(ctx, createMaintainance,
		arg.ID,
		arg.WealthID,
		arg.Type,
		arg.Name,
		arg.CostID,
	)
	var i Maintainances
	err := row.Scan(
		&i.ID,
		&i.WealthID,
		&i.Type,
		&i.Name,
		&i.CostID,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteMaintainance = `-- name: DeleteMaintainance :exec
UPDATE Maintainances
SET deleted = TRUE, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

// DeleteMaintainance
//
//	UPDATE Maintainances
//	SET deleted = TRUE, updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1
func (q *Queries) DeleteMaintainance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMaintainance, id)
	return err
}

const updateMaintainance = `-- name: UpdateMaintainance :one
UPDATE Maintainances
SET wealth_id = $2,
    type = $3,
    name = $4,
    cost_id = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted = FALSE
RETURNING id, wealth_id, type, name, cost_id, deleted, created_at, updated_at
`

type UpdateMaintainanceParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	WealthID uuid.UUID `db:"wealth_id" json:"wealthId"`
	Type     string    `db:"type" json:"type"`
	Name     string    `db:"name" json:"name"`
	CostID   uuid.UUID `db:"cost_id" json:"costId"`
}

// UpdateMaintainance
//
//	UPDATE Maintainances
//	SET wealth_id = $2,
//	    type = $3,
//	    name = $4,
//	    cost_id = $5,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1 AND deleted = FALSE
//	RETURNING id, wealth_id, type, name, cost_id, deleted, created_at, updated_at
func (q *Queries) UpdateMaintainance(ctx context.Context, arg *UpdateMaintainanceParams) (*Maintainances, error) {
	row := q.db.QueryRow(ctx, updateMaintainance,
		arg.ID,
		arg.WealthID,
		arg.Type,
		arg.Name,
		arg.CostID,
	)
	var i Maintainances
	err := row.Scan(
		&i.ID,
		&i.WealthID,
		&i.Type,
		&i.Name,
		&i.CostID,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
