// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maintainances.queries.sql

package v1

import (
	"context"

	"github.com/google/uuid"
)

const getMaintainance = `-- name: GetMaintainance :one
SELECT id, wealth_id, type, name, cost_id, deleted, created_at, updated_at FROM Maintainances
WHERE id = $1 AND deleted = FALSE
`

// Maintainance Read
//
//	SELECT id, wealth_id, type, name, cost_id, deleted, created_at, updated_at FROM Maintainances
//	WHERE id = $1 AND deleted = FALSE
func (q *Queries) GetMaintainance(ctx context.Context, id uuid.UUID) (*Maintainances, error) {
	row := q.db.QueryRow(ctx, getMaintainance, id)
	var i Maintainances
	err := row.Scan(
		&i.ID,
		&i.WealthID,
		&i.Type,
		&i.Name,
		&i.CostID,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMaintainancesByWealth = `-- name: GetMaintainancesByWealth :many
SELECT id, wealth_id, type, name, cost_id, deleted, created_at, updated_at FROM Maintainances
WHERE wealth_id = $1 AND deleted = FALSE
ORDER BY created_at DESC
`

// GetMaintainancesByWealth
//
//	SELECT id, wealth_id, type, name, cost_id, deleted, created_at, updated_at FROM Maintainances
//	WHERE wealth_id = $1 AND deleted = FALSE
//	ORDER BY created_at DESC
func (q *Queries) GetMaintainancesByWealth(ctx context.Context, wealthID uuid.UUID) ([]*Maintainances, error) {
	rows, err := q.db.Query(ctx, getMaintainancesByWealth, wealthID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Maintainances{}
	for rows.Next() {
		var i Maintainances
		if err := rows.Scan(
			&i.ID,
			&i.WealthID,
			&i.Type,
			&i.Name,
			&i.CostID,
			&i.Deleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintainances = `-- name: ListMaintainances :many
SELECT id, wealth_id, type, name, cost_id, deleted, created_at, updated_at FROM Maintainances
WHERE deleted = FALSE
ORDER BY created_at DESC
`

// ListMaintainances
//
//	SELECT id, wealth_id, type, name, cost_id, deleted, created_at, updated_at FROM Maintainances
//	WHERE deleted = FALSE
//	ORDER BY created_at DESC
func (q *Queries) ListMaintainances(ctx context.Context) ([]*Maintainances, error) {
	rows, err := q.db.Query(ctx, listMaintainances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Maintainances{}
	for rows.Next() {
		var i Maintainances
		if err := rows.Scan(
			&i.ID,
			&i.WealthID,
			&i.Type,
			&i.Name,
			&i.CostID,
			&i.Deleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
