// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.commands.sql

package v1

import (
	"context"

	"github.com/google/uuid"
	"go.ssnk.in/inflict/internal/domain"
)

const createMember = `-- name: CreateMember :one
INSERT INTO Members (
  id, name, type, net_worth_id
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, type, net_worth_id, deleted, created_at, updated_at
`

type CreateMemberParams struct {
	ID         uuid.UUID         `db:"id" json:"id"`
	Name       string            `db:"name" json:"name"`
	Type       domain.MemberType `db:"type" json:"type"`
	NetWorthID uuid.UUID         `db:"net_worth_id" json:"netWorthId"`
}

// CreateMember
//
//	INSERT INTO Members (
//	  id, name, type, net_worth_id
//	) VALUES (
//	  $1, $2, $3, $4
//	)
//	RETURNING id, name, type, net_worth_id, deleted, created_at, updated_at
func (q *Queries) CreateMember(ctx context.Context, arg *CreateMemberParams) (*Members, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.NetWorthID,
	)
	var i Members
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.NetWorthID,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteMember = `-- name: DeleteMember :exec
UPDATE Members
SET deleted = TRUE,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

// DeleteMember
//
//	UPDATE Members
//	SET deleted = TRUE,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1
func (q *Queries) DeleteMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMember, id)
	return err
}

const updateMember = `-- name: UpdateMember :one
UPDATE Members
SET name = $2,
    type = $3,
    net_worth_id = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, type, net_worth_id, deleted, created_at, updated_at
`

type UpdateMemberParams struct {
	ID         uuid.UUID         `db:"id" json:"id"`
	Name       string            `db:"name" json:"name"`
	Type       domain.MemberType `db:"type" json:"type"`
	NetWorthID uuid.UUID         `db:"net_worth_id" json:"netWorthId"`
}

// UpdateMember
//
//	UPDATE Members
//	SET name = $2,
//	    type = $3,
//	    net_worth_id = $4,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1
//	RETURNING id, name, type, net_worth_id, deleted, created_at, updated_at
func (q *Queries) UpdateMember(ctx context.Context, arg *UpdateMemberParams) (*Members, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.NetWorthID,
	)
	var i Members
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.NetWorthID,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
