// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.queries.sql

package v1

import (
	"context"

	"github.com/google/uuid"
)

const getMember = `-- name: GetMember :one
SELECT id, name, type, net_worth_id, deleted, created_at, updated_at FROM Members
WHERE id = $1 LIMIT 1
`

// GetMember
//
//	SELECT id, name, type, net_worth_id, deleted, created_at, updated_at FROM Members
//	WHERE id = $1 LIMIT 1
func (q *Queries) GetMember(ctx context.Context, id uuid.UUID) (*Members, error) {
	row := q.db.QueryRow(ctx, getMember, id)
	var i Members
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.NetWorthID,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, name, type, net_worth_id, deleted, created_at, updated_at FROM Members
ORDER BY name
`

// ListMembers
//
//	SELECT id, name, type, net_worth_id, deleted, created_at, updated_at FROM Members
//	ORDER BY name
func (q *Queries) ListMembers(ctx context.Context) ([]*Members, error) {
	rows, err := q.db.Query(ctx, listMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Members{}
	for rows.Next() {
		var i Members
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.NetWorthID,
			&i.Deleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
