// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package v1

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"go.ssnk.in/inflict/internal/domain"
	"google.golang.org/protobuf/types/known/durationpb"
)

type AccomodationType string

const (
	AccomodationTypeOwned  AccomodationType = "Owned"
	AccomodationTypeLeased AccomodationType = "Leased"
	AccomodationTypeRented AccomodationType = "Rented"
	AccomodationTypeShared AccomodationType = "Shared"
)

func (e *AccomodationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccomodationType(s)
	case string:
		*e = AccomodationType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccomodationType: %T", src)
	}
	return nil
}

type NullAccomodationType struct {
	AccomodationType AccomodationType `json:"accomodationType"`
	Valid            bool             `json:"valid"` // Valid is true if AccomodationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccomodationType) Scan(value interface{}) error {
	if value == nil {
		ns.AccomodationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccomodationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccomodationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccomodationType), nil
}

func (e AccomodationType) Valid() bool {
	switch e {
	case AccomodationTypeOwned,
		AccomodationTypeLeased,
		AccomodationTypeRented,
		AccomodationTypeShared:
		return true
	}
	return false
}

func AllAccomodationTypeValues() []AccomodationType {
	return []AccomodationType{
		AccomodationTypeOwned,
		AccomodationTypeLeased,
		AccomodationTypeRented,
		AccomodationTypeShared,
	}
}

type Accomodations struct {
	ID        uuid.UUID               `db:"id" json:"id"`
	MemberID  uuid.UUID               `db:"member_id" json:"memberId"`
	Type      domain.AccomodationType `db:"type" json:"type"`
	Address   pgtype.Text             `db:"address" json:"address"`
	CostID    uuid.UUID               `db:"cost_id" json:"costId"`
	Deleted   bool                    `db:"deleted" json:"deleted"`
	CreatedAt time.Time               `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time               `db:"updated_at" json:"updatedAt"`
}

type Amounts struct {
	ID        uuid.UUID         `db:"id" json:"id"`
	Type      domain.AmountType `db:"type" json:"type"`
	Name      string            `db:"name" json:"name"`
	Sender    string            `db:"sender" json:"sender"`
	Receiver  string            `db:"receiver" json:"receiver"`
	Value     pgtype.Numeric    `db:"value" json:"value"`
	Currency  string            `db:"currency" json:"currency"`
	Deleted   bool              `db:"deleted" json:"deleted"`
	CreatedAt time.Time         `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time         `db:"updated_at" json:"updatedAt"`
}

type Maintainances struct {
	ID        uuid.UUID `db:"id" json:"id"`
	WealthID  uuid.UUID `db:"wealth_id" json:"wealthId"`
	Type      string    `db:"type" json:"type"`
	Name      string    `db:"name" json:"name"`
	CostID    uuid.UUID `db:"cost_id" json:"costId"`
	Deleted   bool      `db:"deleted" json:"deleted"`
	CreatedAt time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time `db:"updated_at" json:"updatedAt"`
}

type Members struct {
	ID         uuid.UUID         `db:"id" json:"id"`
	Name       string            `db:"name" json:"name"`
	Type       domain.MemberType `db:"type" json:"type"`
	NetWorthID uuid.UUID         `db:"net_worth_id" json:"netWorthId"`
	Deleted    bool              `db:"deleted" json:"deleted"`
	CreatedAt  time.Time         `db:"created_at" json:"createdAt"`
	UpdatedAt  time.Time         `db:"updated_at" json:"updatedAt"`
}

type Returns struct {
	ID               uuid.UUID           `db:"id" json:"id"`
	WealthID         uuid.UUID           `db:"wealth_id" json:"wealthId"`
	Name             string              `db:"name" json:"name"`
	RateType         domain.RateType     `db:"rate_type" json:"rateType"`
	RateValue        pgtype.Numeric      `db:"rate_value" json:"rateValue"`
	Duration         durationpb.Duration `db:"duration" json:"duration"`
	MaturityCorpusID uuid.UUID           `db:"maturity_corpus_id" json:"maturityCorpusId"`
	Deleted          bool                `db:"deleted" json:"deleted"`
	CreatedAt        time.Time           `db:"created_at" json:"createdAt"`
	UpdatedAt        time.Time           `db:"updated_at" json:"updatedAt"`
}

type Wealths struct {
	ID        uuid.UUID         `db:"id" json:"id"`
	WorthID   uuid.UUID         `db:"worth_id" json:"worthId"`
	Type      domain.WealthType `db:"type" json:"type"`
	Name      string            `db:"name" json:"name"`
	ValueID   uuid.UUID         `db:"value_id" json:"valueId"`
	Deleted   bool              `db:"deleted" json:"deleted"`
	CreatedAt time.Time         `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time         `db:"updated_at" json:"updatedAt"`
}

type Worths struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Deleted   bool      `db:"deleted" json:"deleted"`
	CreatedAt time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time `db:"updated_at" json:"updatedAt"`
}
