// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: returns.queries.sql

package v1

import (
	"context"

	"github.com/google/uuid"
)

const getReturn = `-- name: GetReturn :one
SELECT id, wealth_id, name, rate_type, rate_value, duration, maturity_corpus_id, deleted, created_at, updated_at FROM Returns
WHERE id = $1 AND deleted = FALSE
`

// Returns Read
//
//	SELECT id, wealth_id, name, rate_type, rate_value, duration, maturity_corpus_id, deleted, created_at, updated_at FROM Returns
//	WHERE id = $1 AND deleted = FALSE
func (q *Queries) GetReturn(ctx context.Context, id uuid.UUID) (*Returns, error) {
	row := q.db.QueryRow(ctx, getReturn, id)
	var i Returns
	err := row.Scan(
		&i.ID,
		&i.WealthID,
		&i.Name,
		&i.RateType,
		&i.RateValue,
		&i.Duration,
		&i.MaturityCorpusID,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getReturnsByWealth = `-- name: GetReturnsByWealth :many
SELECT id, wealth_id, name, rate_type, rate_value, duration, maturity_corpus_id, deleted, created_at, updated_at FROM Returns
WHERE wealth_id = $1 AND deleted = FALSE
ORDER BY created_at DESC
`

// GetReturnsByWealth
//
//	SELECT id, wealth_id, name, rate_type, rate_value, duration, maturity_corpus_id, deleted, created_at, updated_at FROM Returns
//	WHERE wealth_id = $1 AND deleted = FALSE
//	ORDER BY created_at DESC
func (q *Queries) GetReturnsByWealth(ctx context.Context, wealthID uuid.UUID) ([]*Returns, error) {
	rows, err := q.db.Query(ctx, getReturnsByWealth, wealthID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Returns{}
	for rows.Next() {
		var i Returns
		if err := rows.Scan(
			&i.ID,
			&i.WealthID,
			&i.Name,
			&i.RateType,
			&i.RateValue,
			&i.Duration,
			&i.MaturityCorpusID,
			&i.Deleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReturns = `-- name: ListReturns :many
SELECT id, wealth_id, name, rate_type, rate_value, duration, maturity_corpus_id, deleted, created_at, updated_at FROM Returns
WHERE deleted = FALSE
ORDER BY created_at DESC
`

// ListReturns
//
//	SELECT id, wealth_id, name, rate_type, rate_value, duration, maturity_corpus_id, deleted, created_at, updated_at FROM Returns
//	WHERE deleted = FALSE
//	ORDER BY created_at DESC
func (q *Queries) ListReturns(ctx context.Context) ([]*Returns, error) {
	rows, err := q.db.Query(ctx, listReturns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Returns{}
	for rows.Next() {
		var i Returns
		if err := rows.Scan(
			&i.ID,
			&i.WealthID,
			&i.Name,
			&i.RateType,
			&i.RateValue,
			&i.Duration,
			&i.MaturityCorpusID,
			&i.Deleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
