// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: returns.commands.sql

package v1

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"go.ssnk.in/inflict/internal/domain"
	"google.golang.org/protobuf/types/known/durationpb"
)

const createReturn = `-- name: CreateReturn :one
INSERT INTO Returns (id, wealth_id, name, rate_type, rate_value, duration, maturity_corpus_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, wealth_id, name, rate_type, rate_value, duration, maturity_corpus_id, deleted, created_at, updated_at
`

type CreateReturnParams struct {
	ID               uuid.UUID           `db:"id" json:"id"`
	WealthID         uuid.UUID           `db:"wealth_id" json:"wealthId"`
	Name             string              `db:"name" json:"name"`
	RateType         domain.RateType     `db:"rate_type" json:"rateType"`
	RateValue        pgtype.Numeric      `db:"rate_value" json:"rateValue"`
	Duration         durationpb.Duration `db:"duration" json:"duration"`
	MaturityCorpusID uuid.UUID           `db:"maturity_corpus_id" json:"maturityCorpusId"`
}

// Returns CRUD
//
//	INSERT INTO Returns (id, wealth_id, name, rate_type, rate_value, duration, maturity_corpus_id)
//	VALUES ($1, $2, $3, $4, $5, $6, $7)
//	RETURNING id, wealth_id, name, rate_type, rate_value, duration, maturity_corpus_id, deleted, created_at, updated_at
func (q *Queries) CreateReturn(ctx context.Context, arg *CreateReturnParams) (*Returns, error) {
	row := q.db.QueryRow(ctx, createReturn,
		arg.ID,
		arg.WealthID,
		arg.Name,
		arg.RateType,
		arg.RateValue,
		arg.Duration,
		arg.MaturityCorpusID,
	)
	var i Returns
	err := row.Scan(
		&i.ID,
		&i.WealthID,
		&i.Name,
		&i.RateType,
		&i.RateValue,
		&i.Duration,
		&i.MaturityCorpusID,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteReturn = `-- name: DeleteReturn :exec
UPDATE Returns
SET deleted = TRUE, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

// DeleteReturn
//
//	UPDATE Returns
//	SET deleted = TRUE, updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1
func (q *Queries) DeleteReturn(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReturn, id)
	return err
}

const updateReturn = `-- name: UpdateReturn :one
UPDATE Returns
SET wealth_id = $2,
    name = $3,
    rate_type = $4,
    rate_value = $5,
    duration = $6,
    maturity_corpus_id = $7,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted = FALSE
RETURNING id, wealth_id, name, rate_type, rate_value, duration, maturity_corpus_id, deleted, created_at, updated_at
`

type UpdateReturnParams struct {
	ID               uuid.UUID           `db:"id" json:"id"`
	WealthID         uuid.UUID           `db:"wealth_id" json:"wealthId"`
	Name             string              `db:"name" json:"name"`
	RateType         domain.RateType     `db:"rate_type" json:"rateType"`
	RateValue        pgtype.Numeric      `db:"rate_value" json:"rateValue"`
	Duration         durationpb.Duration `db:"duration" json:"duration"`
	MaturityCorpusID uuid.UUID           `db:"maturity_corpus_id" json:"maturityCorpusId"`
}

// UpdateReturn
//
//	UPDATE Returns
//	SET wealth_id = $2,
//	    name = $3,
//	    rate_type = $4,
//	    rate_value = $5,
//	    duration = $6,
//	    maturity_corpus_id = $7,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1 AND deleted = FALSE
//	RETURNING id, wealth_id, name, rate_type, rate_value, duration, maturity_corpus_id, deleted, created_at, updated_at
func (q *Queries) UpdateReturn(ctx context.Context, arg *UpdateReturnParams) (*Returns, error) {
	row := q.db.QueryRow(ctx, updateReturn,
		arg.ID,
		arg.WealthID,
		arg.Name,
		arg.RateType,
		arg.RateValue,
		arg.Duration,
		arg.MaturityCorpusID,
	)
	var i Returns
	err := row.Scan(
		&i.ID,
		&i.WealthID,
		&i.Name,
		&i.RateType,
		&i.RateValue,
		&i.Duration,
		&i.MaturityCorpusID,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
