// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wealths.commands.sql

package v1

import (
	"context"

	"github.com/google/uuid"
	"go.ssnk.in/inflict/internal/domain"
)

const createWealth = `-- name: CreateWealth :one
INSERT INTO Wealths (id, worth_id, type, name, value_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, worth_id, type, name, value_id, deleted, created_at, updated_at
`

type CreateWealthParams struct {
	ID      uuid.UUID         `db:"id" json:"id"`
	WorthID uuid.UUID         `db:"worth_id" json:"worthId"`
	Type    domain.WealthType `db:"type" json:"type"`
	Name    string            `db:"name" json:"name"`
	ValueID uuid.UUID         `db:"value_id" json:"valueId"`
}

// Wealths CRUD
//
//	INSERT INTO Wealths (id, worth_id, type, name, value_id)
//	VALUES ($1, $2, $3, $4, $5)
//	RETURNING id, worth_id, type, name, value_id, deleted, created_at, updated_at
func (q *Queries) CreateWealth(ctx context.Context, arg *CreateWealthParams) (*Wealths, error) {
	row := q.db.QueryRow(ctx, createWealth,
		arg.ID,
		arg.WorthID,
		arg.Type,
		arg.Name,
		arg.ValueID,
	)
	var i Wealths
	err := row.Scan(
		&i.ID,
		&i.WorthID,
		&i.Type,
		&i.Name,
		&i.ValueID,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteWealth = `-- name: DeleteWealth :exec
UPDATE Wealths
SET deleted = TRUE, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

// DeleteWealth
//
//	UPDATE Wealths
//	SET deleted = TRUE, updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1
func (q *Queries) DeleteWealth(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWealth, id)
	return err
}

const updateWealth = `-- name: UpdateWealth :one
UPDATE Wealths
SET worth_id = $2,
    type = $3,
    name = $4,
    value_id = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted = FALSE
RETURNING id, worth_id, type, name, value_id, deleted, created_at, updated_at
`

type UpdateWealthParams struct {
	ID      uuid.UUID         `db:"id" json:"id"`
	WorthID uuid.UUID         `db:"worth_id" json:"worthId"`
	Type    domain.WealthType `db:"type" json:"type"`
	Name    string            `db:"name" json:"name"`
	ValueID uuid.UUID         `db:"value_id" json:"valueId"`
}

// UpdateWealth
//
//	UPDATE Wealths
//	SET worth_id = $2,
//	    type = $3,
//	    name = $4,
//	    value_id = $5,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1 AND deleted = FALSE
//	RETURNING id, worth_id, type, name, value_id, deleted, created_at, updated_at
func (q *Queries) UpdateWealth(ctx context.Context, arg *UpdateWealthParams) (*Wealths, error) {
	row := q.db.QueryRow(ctx, updateWealth,
		arg.ID,
		arg.WorthID,
		arg.Type,
		arg.Name,
		arg.ValueID,
	)
	var i Wealths
	err := row.Scan(
		&i.ID,
		&i.WorthID,
		&i.Type,
		&i.Name,
		&i.ValueID,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
