// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wealths.queries.sql

package v1

import (
	"context"

	"github.com/google/uuid"
	"go.ssnk.in/inflict/internal/domain"
)

const getWealth = `-- name: GetWealth :one
SELECT id, worth_id, type, name, value_id, deleted, created_at, updated_at FROM Wealths
WHERE id = $1 AND deleted = FALSE
`

// Wealths Read
//
//	SELECT id, worth_id, type, name, value_id, deleted, created_at, updated_at FROM Wealths
//	WHERE id = $1 AND deleted = FALSE
func (q *Queries) GetWealth(ctx context.Context, id uuid.UUID) (*Wealths, error) {
	row := q.db.QueryRow(ctx, getWealth, id)
	var i Wealths
	err := row.Scan(
		&i.ID,
		&i.WorthID,
		&i.Type,
		&i.Name,
		&i.ValueID,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getWealthsByType = `-- name: GetWealthsByType :many
SELECT id, worth_id, type, name, value_id, deleted, created_at, updated_at FROM Wealths
WHERE type = $1 AND deleted = FALSE
ORDER BY created_at DESC
`

// GetWealthsByType
//
//	SELECT id, worth_id, type, name, value_id, deleted, created_at, updated_at FROM Wealths
//	WHERE type = $1 AND deleted = FALSE
//	ORDER BY created_at DESC
func (q *Queries) GetWealthsByType(ctx context.Context, type_ domain.WealthType) ([]*Wealths, error) {
	rows, err := q.db.Query(ctx, getWealthsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Wealths{}
	for rows.Next() {
		var i Wealths
		if err := rows.Scan(
			&i.ID,
			&i.WorthID,
			&i.Type,
			&i.Name,
			&i.ValueID,
			&i.Deleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWealthsByWorth = `-- name: GetWealthsByWorth :many
SELECT id, worth_id, type, name, value_id, deleted, created_at, updated_at FROM Wealths
WHERE worth_id = $1 AND deleted = FALSE
ORDER BY created_at DESC
`

// GetWealthsByWorth
//
//	SELECT id, worth_id, type, name, value_id, deleted, created_at, updated_at FROM Wealths
//	WHERE worth_id = $1 AND deleted = FALSE
//	ORDER BY created_at DESC
func (q *Queries) GetWealthsByWorth(ctx context.Context, worthID uuid.UUID) ([]*Wealths, error) {
	rows, err := q.db.Query(ctx, getWealthsByWorth, worthID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Wealths{}
	for rows.Next() {
		var i Wealths
		if err := rows.Scan(
			&i.ID,
			&i.WorthID,
			&i.Type,
			&i.Name,
			&i.ValueID,
			&i.Deleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWealths = `-- name: ListWealths :many
SELECT id, worth_id, type, name, value_id, deleted, created_at, updated_at FROM Wealths
WHERE deleted = FALSE
ORDER BY created_at DESC
`

// ListWealths
//
//	SELECT id, worth_id, type, name, value_id, deleted, created_at, updated_at FROM Wealths
//	WHERE deleted = FALSE
//	ORDER BY created_at DESC
func (q *Queries) ListWealths(ctx context.Context) ([]*Wealths, error) {
	rows, err := q.db.Query(ctx, listWealths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Wealths{}
	for rows.Next() {
		var i Wealths
		if err := rows.Scan(
			&i.ID,
			&i.WorthID,
			&i.Type,
			&i.Name,
			&i.ValueID,
			&i.Deleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
