// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: worths.commands.sql

package v1

import (
	"context"

	"github.com/google/uuid"
)

const createWorth = `-- name: CreateWorth :one
INSERT INTO Worths (id)
VALUES ($1)
RETURNING id, deleted, created_at, updated_at
`

// Worths CRUD
//
//	INSERT INTO Worths (id)
//	VALUES ($1)
//	RETURNING id, deleted, created_at, updated_at
func (q *Queries) CreateWorth(ctx context.Context, id uuid.UUID) (*Worths, error) {
	row := q.db.QueryRow(ctx, createWorth, id)
	var i Worths
	err := row.Scan(
		&i.ID,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteWorth = `-- name: DeleteWorth :exec
UPDATE Worths
SET deleted = TRUE, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

// DeleteWorth
//
//	UPDATE Worths
//	SET deleted = TRUE, updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1
func (q *Queries) DeleteWorth(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorth, id)
	return err
}

const updateWorth = `-- name: UpdateWorth :one
UPDATE Worths
SET updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted = FALSE
RETURNING id, deleted, created_at, updated_at
`

// UpdateWorth
//
//	UPDATE Worths
//	SET updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1 AND deleted = FALSE
//	RETURNING id, deleted, created_at, updated_at
func (q *Queries) UpdateWorth(ctx context.Context, id uuid.UUID) (*Worths, error) {
	row := q.db.QueryRow(ctx, updateWorth, id)
	var i Worths
	err := row.Scan(
		&i.ID,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
