// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: worths.queries.sql

package v1

import (
	"context"

	"github.com/google/uuid"
)

const getWorth = `-- name: GetWorth :one
SELECT id, deleted, created_at, updated_at FROM Worths
WHERE id = $1 AND deleted = FALSE
`

// Worths Read
//
//	SELECT id, deleted, created_at, updated_at FROM Worths
//	WHERE id = $1 AND deleted = FALSE
func (q *Queries) GetWorth(ctx context.Context, id uuid.UUID) (*Worths, error) {
	row := q.db.QueryRow(ctx, getWorth, id)
	var i Worths
	err := row.Scan(
		&i.ID,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listWorths = `-- name: ListWorths :many
SELECT id, deleted, created_at, updated_at FROM Worths
WHERE deleted = FALSE
ORDER BY created_at DESC
`

// ListWorths
//
//	SELECT id, deleted, created_at, updated_at FROM Worths
//	WHERE deleted = FALSE
//	ORDER BY created_at DESC
func (q *Queries) ListWorths(ctx context.Context) ([]*Worths, error) {
	rows, err := q.db.Query(ctx, listWorths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Worths{}
	for rows.Next() {
		var i Worths
		if err := rows.Scan(
			&i.ID,
			&i.Deleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
