// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: protos/v1/api/api.proto

package api

import (
	entities "go.ssnk.in/inflict/schema/protos/v1/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityT int32

const (
	EntityT_ENTITY_AMOUNT       EntityT = 0
	EntityT_ENTITY_MAINTAINANCE EntityT = 1
	EntityT_ENTITY_RETURN       EntityT = 2
	EntityT_ENTITY_WEALTH       EntityT = 3
	EntityT_ENTITY_WORTH        EntityT = 4
)

// Enum value maps for EntityT.
var (
	EntityT_name = map[int32]string{
		0: "ENTITY_AMOUNT",
		1: "ENTITY_MAINTAINANCE",
		2: "ENTITY_RETURN",
		3: "ENTITY_WEALTH",
		4: "ENTITY_WORTH",
	}
	EntityT_value = map[string]int32{
		"ENTITY_AMOUNT":       0,
		"ENTITY_MAINTAINANCE": 1,
		"ENTITY_RETURN":       2,
		"ENTITY_WEALTH":       3,
		"ENTITY_WORTH":        4,
	}
)

func (x EntityT) Enum() *EntityT {
	p := new(EntityT)
	*p = x
	return p
}

func (x EntityT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityT) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_v1_api_api_proto_enumTypes[0].Descriptor()
}

func (EntityT) Type() protoreflect.EnumType {
	return &file_protos_v1_api_api_proto_enumTypes[0]
}

func (x EntityT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityT.Descriptor instead.
func (EntityT) EnumDescriptor() ([]byte, []int) {
	return file_protos_v1_api_api_proto_rawDescGZIP(), []int{0}
}

type StatusCode int32

const (
	// Default value. In Protobuf, the 0 value is required as the first element.
	// This serves as a safety catch for uninitialized fields.
	StatusCode_UNSPECIFIED           StatusCode = 0
	StatusCode_OK                    StatusCode = 200
	StatusCode_CREATED               StatusCode = 201
	StatusCode_NO_CONTENT            StatusCode = 204
	StatusCode_MOVED_PERMANENTLY     StatusCode = 301
	StatusCode_TEMPORARY_REDIRECT    StatusCode = 307
	StatusCode_BAD_REQUEST           StatusCode = 400
	StatusCode_UNAUTHORIZED          StatusCode = 401
	StatusCode_FORBIDDEN             StatusCode = 403
	StatusCode_NOT_FOUND             StatusCode = 404
	StatusCode_CONFLICT              StatusCode = 409
	StatusCode_TOO_MANY_REQUESTS     StatusCode = 429
	StatusCode_CLIENT_CLOSED_REQUEST StatusCode = 499
	StatusCode_INTERNAL_SERVER_ERROR StatusCode = 500
	StatusCode_SERVICE_UNAVAILABLE   StatusCode = 503
	StatusCode_GATEWAY_TIMEOUT       StatusCode = 504
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0:   "UNSPECIFIED",
		200: "OK",
		201: "CREATED",
		204: "NO_CONTENT",
		301: "MOVED_PERMANENTLY",
		307: "TEMPORARY_REDIRECT",
		400: "BAD_REQUEST",
		401: "UNAUTHORIZED",
		403: "FORBIDDEN",
		404: "NOT_FOUND",
		409: "CONFLICT",
		429: "TOO_MANY_REQUESTS",
		499: "CLIENT_CLOSED_REQUEST",
		500: "INTERNAL_SERVER_ERROR",
		503: "SERVICE_UNAVAILABLE",
		504: "GATEWAY_TIMEOUT",
	}
	StatusCode_value = map[string]int32{
		"UNSPECIFIED":           0,
		"OK":                    200,
		"CREATED":               201,
		"NO_CONTENT":            204,
		"MOVED_PERMANENTLY":     301,
		"TEMPORARY_REDIRECT":    307,
		"BAD_REQUEST":           400,
		"UNAUTHORIZED":          401,
		"FORBIDDEN":             403,
		"NOT_FOUND":             404,
		"CONFLICT":              409,
		"TOO_MANY_REQUESTS":     429,
		"CLIENT_CLOSED_REQUEST": 499,
		"INTERNAL_SERVER_ERROR": 500,
		"SERVICE_UNAVAILABLE":   503,
		"GATEWAY_TIMEOUT":       504,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_v1_api_api_proto_enumTypes[1].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_protos_v1_api_api_proto_enumTypes[1]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_protos_v1_api_api_proto_rawDescGZIP(), []int{1}
}

type Request struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Entity EntityT                `protobuf:"varint,1,opt,name=entity,proto3,enum=inflict.v1.api.EntityT" json:"entity,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Request_Id
	//	*Request_Amount
	//	*Request_Maintainance
	//	*Request_Return
	//	*Request_Wealth
	//	*Request_Worth
	Payload       isRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_protos_v1_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_protos_v1_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetEntity() EntityT {
	if x != nil {
		return x.Entity
	}
	return EntityT_ENTITY_AMOUNT
}

func (x *Request) GetPayload() isRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetId() string {
	if x != nil {
		if x, ok := x.Payload.(*Request_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *Request) GetAmount() *entities.Amount {
	if x != nil {
		if x, ok := x.Payload.(*Request_Amount); ok {
			return x.Amount
		}
	}
	return nil
}

func (x *Request) GetMaintainance() *entities.Maintainance {
	if x != nil {
		if x, ok := x.Payload.(*Request_Maintainance); ok {
			return x.Maintainance
		}
	}
	return nil
}

func (x *Request) GetReturn() *entities.Return {
	if x != nil {
		if x, ok := x.Payload.(*Request_Return); ok {
			return x.Return
		}
	}
	return nil
}

func (x *Request) GetWealth() *entities.Wealth {
	if x != nil {
		if x, ok := x.Payload.(*Request_Wealth); ok {
			return x.Wealth
		}
	}
	return nil
}

func (x *Request) GetWorth() *entities.Worth {
	if x != nil {
		if x, ok := x.Payload.(*Request_Worth); ok {
			return x.Worth
		}
	}
	return nil
}

type isRequest_Payload interface {
	isRequest_Payload()
}

type Request_Id struct {
	Id string `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
}

type Request_Amount struct {
	Amount *entities.Amount `protobuf:"bytes,3,opt,name=amount,proto3,oneof"`
}

type Request_Maintainance struct {
	Maintainance *entities.Maintainance `protobuf:"bytes,4,opt,name=maintainance,proto3,oneof"`
}

type Request_Return struct {
	Return *entities.Return `protobuf:"bytes,5,opt,name=return,proto3,oneof"`
}

type Request_Wealth struct {
	Wealth *entities.Wealth `protobuf:"bytes,6,opt,name=wealth,proto3,oneof"`
}

type Request_Worth struct {
	Worth *entities.Worth `protobuf:"bytes,7,opt,name=worth,proto3,oneof"`
}

func (*Request_Id) isRequest_Payload() {}

func (*Request_Amount) isRequest_Payload() {}

func (*Request_Maintainance) isRequest_Payload() {}

func (*Request_Return) isRequest_Payload() {}

func (*Request_Wealth) isRequest_Payload() {}

func (*Request_Worth) isRequest_Payload() {}

type Response struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Response_Id
	//	*Response_Amount
	//	*Response_Maintainance
	//	*Response_Return
	//	*Response_Wealth
	//	*Response_Worth
	Payload       isResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_protos_v1_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protos_v1_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Response) GetPayload() isResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Response) GetId() string {
	if x != nil {
		if x, ok := x.Payload.(*Response_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *Response) GetAmount() *entities.Amount {
	if x != nil {
		if x, ok := x.Payload.(*Response_Amount); ok {
			return x.Amount
		}
	}
	return nil
}

func (x *Response) GetMaintainance() *entities.Maintainance {
	if x != nil {
		if x, ok := x.Payload.(*Response_Maintainance); ok {
			return x.Maintainance
		}
	}
	return nil
}

func (x *Response) GetReturn() *entities.Return {
	if x != nil {
		if x, ok := x.Payload.(*Response_Return); ok {
			return x.Return
		}
	}
	return nil
}

func (x *Response) GetWealth() *entities.Wealth {
	if x != nil {
		if x, ok := x.Payload.(*Response_Wealth); ok {
			return x.Wealth
		}
	}
	return nil
}

func (x *Response) GetWorth() *entities.Worth {
	if x != nil {
		if x, ok := x.Payload.(*Response_Worth); ok {
			return x.Worth
		}
	}
	return nil
}

type isResponse_Payload interface {
	isResponse_Payload()
}

type Response_Id struct {
	Id string `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
}

type Response_Amount struct {
	Amount *entities.Amount `protobuf:"bytes,3,opt,name=amount,proto3,oneof"`
}

type Response_Maintainance struct {
	Maintainance *entities.Maintainance `protobuf:"bytes,4,opt,name=maintainance,proto3,oneof"`
}

type Response_Return struct {
	Return *entities.Return `protobuf:"bytes,5,opt,name=return,proto3,oneof"`
}

type Response_Wealth struct {
	Wealth *entities.Wealth `protobuf:"bytes,6,opt,name=wealth,proto3,oneof"`
}

type Response_Worth struct {
	Worth *entities.Worth `protobuf:"bytes,7,opt,name=worth,proto3,oneof"`
}

func (*Response_Id) isResponse_Payload() {}

func (*Response_Amount) isResponse_Payload() {}

func (*Response_Maintainance) isResponse_Payload() {}

func (*Response_Return) isResponse_Payload() {}

func (*Response_Wealth) isResponse_Payload() {}

func (*Response_Worth) isResponse_Payload() {}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          StatusCode             `protobuf:"varint,1,opt,name=code,proto3,enum=inflict.v1.api.StatusCode" json:"code,omitempty"`
	Message       *Error                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_protos_v1_api_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_api_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_protos_v1_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *Status) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_UNSPECIFIED
}

func (x *Status) GetMessage() *Error {
	if x != nil {
		return x.Message
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_protos_v1_api_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_api_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_protos_v1_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_protos_v1_api_api_proto protoreflect.FileDescriptor

const file_protos_v1_api_api_proto_rawDesc = "" +
	"\n" +
	"\x17protos/v1/api/api.proto\x12\x0einflict.v1.api\x1a\x1fprotos/v1/entities/common.proto\x1a\x1fprotos/v1/entities/entity.proto\x1a\x1fprotos/v1/entities/family.proto\x1a\x1fprotos/v1/entities/member.proto\x1a\x1fprotos/v1/entities/wealth.proto\"\xf9\x02\n" +
	"\aRequest\x12/\n" +
	"\x06entity\x18\x01 \x01(\x0e2\x17.inflict.v1.api.EntityTR\x06entity\x12\x10\n" +
	"\x02id\x18\x02 \x01(\tH\x00R\x02id\x125\n" +
	"\x06amount\x18\x03 \x01(\v2\x1b.inflict.v1.entities.AmountH\x00R\x06amount\x12G\n" +
	"\fmaintainance\x18\x04 \x01(\v2!.inflict.v1.entities.MaintainanceH\x00R\fmaintainance\x125\n" +
	"\x06return\x18\x05 \x01(\v2\x1b.inflict.v1.entities.ReturnH\x00R\x06return\x125\n" +
	"\x06wealth\x18\x06 \x01(\v2\x1b.inflict.v1.entities.WealthH\x00R\x06wealth\x122\n" +
	"\x05worth\x18\a \x01(\v2\x1a.inflict.v1.entities.WorthH\x00R\x05worthB\t\n" +
	"\apayload\"\xf9\x02\n" +
	"\bResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.inflict.v1.api.StatusR\x06status\x12\x10\n" +
	"\x02id\x18\x02 \x01(\tH\x00R\x02id\x125\n" +
	"\x06amount\x18\x03 \x01(\v2\x1b.inflict.v1.entities.AmountH\x00R\x06amount\x12G\n" +
	"\fmaintainance\x18\x04 \x01(\v2!.inflict.v1.entities.MaintainanceH\x00R\fmaintainance\x125\n" +
	"\x06return\x18\x05 \x01(\v2\x1b.inflict.v1.entities.ReturnH\x00R\x06return\x125\n" +
	"\x06wealth\x18\x06 \x01(\v2\x1b.inflict.v1.entities.WealthH\x00R\x06wealth\x122\n" +
	"\x05worth\x18\a \x01(\v2\x1a.inflict.v1.entities.WorthH\x00R\x05worthB\t\n" +
	"\apayload\"i\n" +
	"\x06Status\x12.\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1a.inflict.v1.api.StatusCodeR\x04code\x12/\n" +
	"\amessage\x18\x02 \x01(\v2\x15.inflict.v1.api.ErrorR\amessage\"C\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription*m\n" +
	"\aEntityT\x12\x11\n" +
	"\rENTITY_AMOUNT\x10\x00\x12\x17\n" +
	"\x13ENTITY_MAINTAINANCE\x10\x01\x12\x11\n" +
	"\rENTITY_RETURN\x10\x02\x12\x11\n" +
	"\rENTITY_WEALTH\x10\x03\x12\x10\n" +
	"\fENTITY_WORTH\x10\x04*\xca\x02\n" +
	"\n" +
	"StatusCode\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\a\n" +
	"\x02OK\x10\xc8\x01\x12\f\n" +
	"\aCREATED\x10\xc9\x01\x12\x0f\n" +
	"\n" +
	"NO_CONTENT\x10\xcc\x01\x12\x16\n" +
	"\x11MOVED_PERMANENTLY\x10\xad\x02\x12\x17\n" +
	"\x12TEMPORARY_REDIRECT\x10\xb3\x02\x12\x10\n" +
	"\vBAD_REQUEST\x10\x90\x03\x12\x11\n" +
	"\fUNAUTHORIZED\x10\x91\x03\x12\x0e\n" +
	"\tFORBIDDEN\x10\x93\x03\x12\x0e\n" +
	"\tNOT_FOUND\x10\x94\x03\x12\r\n" +
	"\bCONFLICT\x10\x99\x03\x12\x16\n" +
	"\x11TOO_MANY_REQUESTS\x10\xad\x03\x12\x1a\n" +
	"\x15CLIENT_CLOSED_REQUEST\x10\xf3\x03\x12\x1a\n" +
	"\x15INTERNAL_SERVER_ERROR\x10\xf4\x03\x12\x18\n" +
	"\x13SERVICE_UNAVAILABLE\x10\xf7\x03\x12\x14\n" +
	"\x0fGATEWAY_TIMEOUT\x10\xf8\x03B\xa1\x01\n" +
	"\x12com.inflict.v1.apiB\bApiProtoP\x01Z'go.ssnk.in/inflict/schema/protos/v1/api\xa2\x02\x03IVA\xaa\x02\x0eInflict.V1.Api\xca\x02\x0eInflict\\V1\\Api\xe2\x02\x1aInflict\\V1\\Api\\GPBMetadata\xea\x02\x10Inflict::V1::Apib\x06proto3"

var (
	file_protos_v1_api_api_proto_rawDescOnce sync.Once
	file_protos_v1_api_api_proto_rawDescData []byte
)

func file_protos_v1_api_api_proto_rawDescGZIP() []byte {
	file_protos_v1_api_api_proto_rawDescOnce.Do(func() {
		file_protos_v1_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_v1_api_api_proto_rawDesc), len(file_protos_v1_api_api_proto_rawDesc)))
	})
	return file_protos_v1_api_api_proto_rawDescData
}

var file_protos_v1_api_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_v1_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_v1_api_api_proto_goTypes = []any{
	(EntityT)(0),                  // 0: inflict.v1.api.EntityT
	(StatusCode)(0),               // 1: inflict.v1.api.StatusCode
	(*Request)(nil),               // 2: inflict.v1.api.Request
	(*Response)(nil),              // 3: inflict.v1.api.Response
	(*Status)(nil),                // 4: inflict.v1.api.Status
	(*Error)(nil),                 // 5: inflict.v1.api.Error
	(*entities.Amount)(nil),       // 6: inflict.v1.entities.Amount
	(*entities.Maintainance)(nil), // 7: inflict.v1.entities.Maintainance
	(*entities.Return)(nil),       // 8: inflict.v1.entities.Return
	(*entities.Wealth)(nil),       // 9: inflict.v1.entities.Wealth
	(*entities.Worth)(nil),        // 10: inflict.v1.entities.Worth
}
var file_protos_v1_api_api_proto_depIdxs = []int32{
	0,  // 0: inflict.v1.api.Request.entity:type_name -> inflict.v1.api.EntityT
	6,  // 1: inflict.v1.api.Request.amount:type_name -> inflict.v1.entities.Amount
	7,  // 2: inflict.v1.api.Request.maintainance:type_name -> inflict.v1.entities.Maintainance
	8,  // 3: inflict.v1.api.Request.return:type_name -> inflict.v1.entities.Return
	9,  // 4: inflict.v1.api.Request.wealth:type_name -> inflict.v1.entities.Wealth
	10, // 5: inflict.v1.api.Request.worth:type_name -> inflict.v1.entities.Worth
	4,  // 6: inflict.v1.api.Response.status:type_name -> inflict.v1.api.Status
	6,  // 7: inflict.v1.api.Response.amount:type_name -> inflict.v1.entities.Amount
	7,  // 8: inflict.v1.api.Response.maintainance:type_name -> inflict.v1.entities.Maintainance
	8,  // 9: inflict.v1.api.Response.return:type_name -> inflict.v1.entities.Return
	9,  // 10: inflict.v1.api.Response.wealth:type_name -> inflict.v1.entities.Wealth
	10, // 11: inflict.v1.api.Response.worth:type_name -> inflict.v1.entities.Worth
	1,  // 12: inflict.v1.api.Status.code:type_name -> inflict.v1.api.StatusCode
	5,  // 13: inflict.v1.api.Status.message:type_name -> inflict.v1.api.Error
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_protos_v1_api_api_proto_init() }
func file_protos_v1_api_api_proto_init() {
	if File_protos_v1_api_api_proto != nil {
		return
	}
	file_protos_v1_api_api_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_Id)(nil),
		(*Request_Amount)(nil),
		(*Request_Maintainance)(nil),
		(*Request_Return)(nil),
		(*Request_Wealth)(nil),
		(*Request_Worth)(nil),
	}
	file_protos_v1_api_api_proto_msgTypes[1].OneofWrappers = []any{
		(*Response_Id)(nil),
		(*Response_Amount)(nil),
		(*Response_Maintainance)(nil),
		(*Response_Return)(nil),
		(*Response_Wealth)(nil),
		(*Response_Worth)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_v1_api_api_proto_rawDesc), len(file_protos_v1_api_api_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_v1_api_api_proto_goTypes,
		DependencyIndexes: file_protos_v1_api_api_proto_depIdxs,
		EnumInfos:         file_protos_v1_api_api_proto_enumTypes,
		MessageInfos:      file_protos_v1_api_api_proto_msgTypes,
	}.Build()
	File_protos_v1_api_api_proto = out.File
	file_protos_v1_api_api_proto_goTypes = nil
	file_protos_v1_api_api_proto_depIdxs = nil
}
