// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protos/v1/api/api.proto

package api

import (
	entities "go.ssnk.in/inflict/schema/protos/v1/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request_Type int32

const (
	Request_TYPE_UNSPECIFIED  Request_Type = 0
	Request_TYPE_AMOUNT       Request_Type = 1
	Request_TYPE_MAINTAINANCE Request_Type = 2
	Request_TYPE_RETURN       Request_Type = 3
	Request_TYPE_WEALTH       Request_Type = 4
	Request_TYPE_WORTH        Request_Type = 5
)

// Enum value maps for Request_Type.
var (
	Request_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_AMOUNT",
		2: "TYPE_MAINTAINANCE",
		3: "TYPE_RETURN",
		4: "TYPE_WEALTH",
		5: "TYPE_WORTH",
	}
	Request_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":  0,
		"TYPE_AMOUNT":       1,
		"TYPE_MAINTAINANCE": 2,
		"TYPE_RETURN":       3,
		"TYPE_WEALTH":       4,
		"TYPE_WORTH":        5,
	}
)

func (x Request_Type) Enum() *Request_Type {
	p := new(Request_Type)
	*p = x
	return p
}

func (x Request_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Request_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_v1_api_api_proto_enumTypes[0].Descriptor()
}

func (Request_Type) Type() protoreflect.EnumType {
	return &file_protos_v1_api_api_proto_enumTypes[0]
}

func (x Request_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Request_Type.Descriptor instead.
func (Request_Type) EnumDescriptor() ([]byte, []int) {
	return file_protos_v1_api_api_proto_rawDescGZIP(), []int{0, 0}
}

type Status_Code int32

const (
	Status_CODE_UNSPECIFIED           Status_Code = 0
	Status_CODE_OK                    Status_Code = 200
	Status_CODE_CREATED               Status_Code = 201
	Status_CODE_NO_CONTENT            Status_Code = 204
	Status_CODE_MOVED_PERMANENTLY     Status_Code = 301
	Status_CODE_TEMPORARY_REDIRECT    Status_Code = 307
	Status_CODE_BAD_REQUEST           Status_Code = 400
	Status_CODE_UNAUTHORIZED          Status_Code = 401
	Status_CODE_FORBIDDEN             Status_Code = 403
	Status_CODE_NOT_FOUND             Status_Code = 404
	Status_CODE_CONFLICT              Status_Code = 409
	Status_CODE_TOO_MANY_REQUESTS     Status_Code = 429
	Status_CODE_CLIENT_CLOSED_REQUEST Status_Code = 499
	Status_CODE_INTERNAL_SERVER_ERROR Status_Code = 500
	Status_CODE_SERVICE_UNAVAILABLE   Status_Code = 503
	Status_CODE_GATEWAY_TIMEOUT       Status_Code = 504
)

// Enum value maps for Status_Code.
var (
	Status_Code_name = map[int32]string{
		0:   "CODE_UNSPECIFIED",
		200: "CODE_OK",
		201: "CODE_CREATED",
		204: "CODE_NO_CONTENT",
		301: "CODE_MOVED_PERMANENTLY",
		307: "CODE_TEMPORARY_REDIRECT",
		400: "CODE_BAD_REQUEST",
		401: "CODE_UNAUTHORIZED",
		403: "CODE_FORBIDDEN",
		404: "CODE_NOT_FOUND",
		409: "CODE_CONFLICT",
		429: "CODE_TOO_MANY_REQUESTS",
		499: "CODE_CLIENT_CLOSED_REQUEST",
		500: "CODE_INTERNAL_SERVER_ERROR",
		503: "CODE_SERVICE_UNAVAILABLE",
		504: "CODE_GATEWAY_TIMEOUT",
	}
	Status_Code_value = map[string]int32{
		"CODE_UNSPECIFIED":           0,
		"CODE_OK":                    200,
		"CODE_CREATED":               201,
		"CODE_NO_CONTENT":            204,
		"CODE_MOVED_PERMANENTLY":     301,
		"CODE_TEMPORARY_REDIRECT":    307,
		"CODE_BAD_REQUEST":           400,
		"CODE_UNAUTHORIZED":          401,
		"CODE_FORBIDDEN":             403,
		"CODE_NOT_FOUND":             404,
		"CODE_CONFLICT":              409,
		"CODE_TOO_MANY_REQUESTS":     429,
		"CODE_CLIENT_CLOSED_REQUEST": 499,
		"CODE_INTERNAL_SERVER_ERROR": 500,
		"CODE_SERVICE_UNAVAILABLE":   503,
		"CODE_GATEWAY_TIMEOUT":       504,
	}
)

func (x Status_Code) Enum() *Status_Code {
	p := new(Status_Code)
	*p = x
	return p
}

func (x Status_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_v1_api_api_proto_enumTypes[1].Descriptor()
}

func (Status_Code) Type() protoreflect.EnumType {
	return &file_protos_v1_api_api_proto_enumTypes[1]
}

func (x Status_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status_Code.Descriptor instead.
func (Status_Code) EnumDescriptor() ([]byte, []int) {
	return file_protos_v1_api_api_proto_rawDescGZIP(), []int{2, 0}
}

type Request struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Entity Request_Type           `protobuf:"varint,1,opt,name=entity,proto3,enum=inflict.v1.api.Request_Type" json:"entity,omitempty"`
	Id     string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Request_Amount
	//	*Request_Maintainance
	//	*Request_Return
	//	*Request_Wealth
	//	*Request_Worth
	Payload       isRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_protos_v1_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_protos_v1_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetEntity() Request_Type {
	if x != nil {
		return x.Entity
	}
	return Request_TYPE_UNSPECIFIED
}

func (x *Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Request) GetPayload() isRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetAmount() *entities.Amount {
	if x != nil {
		if x, ok := x.Payload.(*Request_Amount); ok {
			return x.Amount
		}
	}
	return nil
}

func (x *Request) GetMaintainance() *entities.Maintainance {
	if x != nil {
		if x, ok := x.Payload.(*Request_Maintainance); ok {
			return x.Maintainance
		}
	}
	return nil
}

func (x *Request) GetReturn() *entities.Return {
	if x != nil {
		if x, ok := x.Payload.(*Request_Return); ok {
			return x.Return
		}
	}
	return nil
}

func (x *Request) GetWealth() *entities.Wealth {
	if x != nil {
		if x, ok := x.Payload.(*Request_Wealth); ok {
			return x.Wealth
		}
	}
	return nil
}

func (x *Request) GetWorth() *entities.Worth {
	if x != nil {
		if x, ok := x.Payload.(*Request_Worth); ok {
			return x.Worth
		}
	}
	return nil
}

type isRequest_Payload interface {
	isRequest_Payload()
}

type Request_Amount struct {
	Amount *entities.Amount `protobuf:"bytes,3,opt,name=amount,proto3,oneof"`
}

type Request_Maintainance struct {
	Maintainance *entities.Maintainance `protobuf:"bytes,4,opt,name=maintainance,proto3,oneof"`
}

type Request_Return struct {
	Return *entities.Return `protobuf:"bytes,5,opt,name=return,proto3,oneof"`
}

type Request_Wealth struct {
	Wealth *entities.Wealth `protobuf:"bytes,6,opt,name=wealth,proto3,oneof"`
}

type Request_Worth struct {
	Worth *entities.Worth `protobuf:"bytes,7,opt,name=worth,proto3,oneof"`
}

func (*Request_Amount) isRequest_Payload() {}

func (*Request_Maintainance) isRequest_Payload() {}

func (*Request_Return) isRequest_Payload() {}

func (*Request_Wealth) isRequest_Payload() {}

func (*Request_Worth) isRequest_Payload() {}

type Response struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Id     string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Response_Amount
	//	*Response_Maintainance
	//	*Response_Return
	//	*Response_Wealth
	//	*Response_Worth
	Payload       isResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_protos_v1_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protos_v1_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Response) GetPayload() isResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Response) GetAmount() *entities.Amount {
	if x != nil {
		if x, ok := x.Payload.(*Response_Amount); ok {
			return x.Amount
		}
	}
	return nil
}

func (x *Response) GetMaintainance() *entities.Maintainance {
	if x != nil {
		if x, ok := x.Payload.(*Response_Maintainance); ok {
			return x.Maintainance
		}
	}
	return nil
}

func (x *Response) GetReturn() *entities.Return {
	if x != nil {
		if x, ok := x.Payload.(*Response_Return); ok {
			return x.Return
		}
	}
	return nil
}

func (x *Response) GetWealth() *entities.Wealth {
	if x != nil {
		if x, ok := x.Payload.(*Response_Wealth); ok {
			return x.Wealth
		}
	}
	return nil
}

func (x *Response) GetWorth() *entities.Worth {
	if x != nil {
		if x, ok := x.Payload.(*Response_Worth); ok {
			return x.Worth
		}
	}
	return nil
}

type isResponse_Payload interface {
	isResponse_Payload()
}

type Response_Amount struct {
	Amount *entities.Amount `protobuf:"bytes,3,opt,name=amount,proto3,oneof"`
}

type Response_Maintainance struct {
	Maintainance *entities.Maintainance `protobuf:"bytes,4,opt,name=maintainance,proto3,oneof"`
}

type Response_Return struct {
	Return *entities.Return `protobuf:"bytes,5,opt,name=return,proto3,oneof"`
}

type Response_Wealth struct {
	Wealth *entities.Wealth `protobuf:"bytes,6,opt,name=wealth,proto3,oneof"`
}

type Response_Worth struct {
	Worth *entities.Worth `protobuf:"bytes,7,opt,name=worth,proto3,oneof"`
}

func (*Response_Amount) isResponse_Payload() {}

func (*Response_Maintainance) isResponse_Payload() {}

func (*Response_Return) isResponse_Payload() {}

func (*Response_Wealth) isResponse_Payload() {}

func (*Response_Worth) isResponse_Payload() {}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Status_Code            `protobuf:"varint,1,opt,name=code,proto3,enum=inflict.v1.api.Status_Code" json:"code,omitempty"`
	Message       *Error                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_protos_v1_api_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_api_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_protos_v1_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *Status) GetCode() Status_Code {
	if x != nil {
		return x.Code
	}
	return Status_CODE_UNSPECIFIED
}

func (x *Status) GetMessage() *Error {
	if x != nil {
		return x.Message
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_protos_v1_api_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_api_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_protos_v1_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_protos_v1_api_api_proto protoreflect.FileDescriptor

const file_protos_v1_api_api_proto_rawDesc = "" +
	"\n" +
	"\x17protos/v1/api/api.proto\x12\x0einflict.v1.api\x1a\x1fprotos/v1/entities/amount.proto\x1a\x1fprotos/v1/entities/entity.proto\x1a\x1fprotos/v1/entities/family.proto\x1a%protos/v1/entities/maintainance.proto\x1a\x1fprotos/v1/entities/member.proto\x1a\x1fprotos/v1/entities/wealth.proto\"\xf4\x03\n" +
	"\aRequest\x124\n" +
	"\x06entity\x18\x01 \x01(\x0e2\x1c.inflict.v1.api.Request.TypeR\x06entity\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x125\n" +
	"\x06amount\x18\x03 \x01(\v2\x1b.inflict.v1.entities.AmountH\x00R\x06amount\x12G\n" +
	"\fmaintainance\x18\x04 \x01(\v2!.inflict.v1.entities.MaintainanceH\x00R\fmaintainance\x125\n" +
	"\x06return\x18\x05 \x01(\v2\x1b.inflict.v1.entities.ReturnH\x00R\x06return\x125\n" +
	"\x06wealth\x18\x06 \x01(\v2\x1b.inflict.v1.entities.WealthH\x00R\x06wealth\x122\n" +
	"\x05worth\x18\a \x01(\v2\x1a.inflict.v1.entities.WorthH\x00R\x05worth\"v\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vTYPE_AMOUNT\x10\x01\x12\x15\n" +
	"\x11TYPE_MAINTAINANCE\x10\x02\x12\x0f\n" +
	"\vTYPE_RETURN\x10\x03\x12\x0f\n" +
	"\vTYPE_WEALTH\x10\x04\x12\x0e\n" +
	"\n" +
	"TYPE_WORTH\x10\x05B\t\n" +
	"\apayload\"\xf7\x02\n" +
	"\bResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x16.inflict.v1.api.StatusR\x06status\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x125\n" +
	"\x06amount\x18\x03 \x01(\v2\x1b.inflict.v1.entities.AmountH\x00R\x06amount\x12G\n" +
	"\fmaintainance\x18\x04 \x01(\v2!.inflict.v1.entities.MaintainanceH\x00R\fmaintainance\x125\n" +
	"\x06return\x18\x05 \x01(\v2\x1b.inflict.v1.entities.ReturnH\x00R\x06return\x125\n" +
	"\x06wealth\x18\x06 \x01(\v2\x1b.inflict.v1.entities.WealthH\x00R\x06wealth\x122\n" +
	"\x05worth\x18\a \x01(\v2\x1a.inflict.v1.entities.WorthH\x00R\x05worthB\t\n" +
	"\apayload\"\x81\x04\n" +
	"\x06Status\x12/\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1b.inflict.v1.api.Status.CodeR\x04code\x12/\n" +
	"\amessage\x18\x02 \x01(\v2\x15.inflict.v1.api.ErrorR\amessage\"\x94\x03\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\aCODE_OK\x10\xc8\x01\x12\x11\n" +
	"\fCODE_CREATED\x10\xc9\x01\x12\x14\n" +
	"\x0fCODE_NO_CONTENT\x10\xcc\x01\x12\x1b\n" +
	"\x16CODE_MOVED_PERMANENTLY\x10\xad\x02\x12\x1c\n" +
	"\x17CODE_TEMPORARY_REDIRECT\x10\xb3\x02\x12\x15\n" +
	"\x10CODE_BAD_REQUEST\x10\x90\x03\x12\x16\n" +
	"\x11CODE_UNAUTHORIZED\x10\x91\x03\x12\x13\n" +
	"\x0eCODE_FORBIDDEN\x10\x93\x03\x12\x13\n" +
	"\x0eCODE_NOT_FOUND\x10\x94\x03\x12\x12\n" +
	"\rCODE_CONFLICT\x10\x99\x03\x12\x1b\n" +
	"\x16CODE_TOO_MANY_REQUESTS\x10\xad\x03\x12\x1f\n" +
	"\x1aCODE_CLIENT_CLOSED_REQUEST\x10\xf3\x03\x12\x1f\n" +
	"\x1aCODE_INTERNAL_SERVER_ERROR\x10\xf4\x03\x12\x1d\n" +
	"\x18CODE_SERVICE_UNAVAILABLE\x10\xf7\x03\x12\x19\n" +
	"\x14CODE_GATEWAY_TIMEOUT\x10\xf8\x03\"C\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescriptionB\xa1\x01\n" +
	"\x12com.inflict.v1.apiB\bApiProtoP\x01Z'go.ssnk.in/inflict/schema/protos/v1/api\xa2\x02\x03IVA\xaa\x02\x0eInflict.V1.Api\xca\x02\x0eInflict\\V1\\Api\xe2\x02\x1aInflict\\V1\\Api\\GPBMetadata\xea\x02\x10Inflict::V1::Apib\x06proto3"

var (
	file_protos_v1_api_api_proto_rawDescOnce sync.Once
	file_protos_v1_api_api_proto_rawDescData []byte
)

func file_protos_v1_api_api_proto_rawDescGZIP() []byte {
	file_protos_v1_api_api_proto_rawDescOnce.Do(func() {
		file_protos_v1_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_v1_api_api_proto_rawDesc), len(file_protos_v1_api_api_proto_rawDesc)))
	})
	return file_protos_v1_api_api_proto_rawDescData
}

var file_protos_v1_api_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_v1_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_v1_api_api_proto_goTypes = []any{
	(Request_Type)(0),             // 0: inflict.v1.api.Request.Type
	(Status_Code)(0),              // 1: inflict.v1.api.Status.Code
	(*Request)(nil),               // 2: inflict.v1.api.Request
	(*Response)(nil),              // 3: inflict.v1.api.Response
	(*Status)(nil),                // 4: inflict.v1.api.Status
	(*Error)(nil),                 // 5: inflict.v1.api.Error
	(*entities.Amount)(nil),       // 6: inflict.v1.entities.Amount
	(*entities.Maintainance)(nil), // 7: inflict.v1.entities.Maintainance
	(*entities.Return)(nil),       // 8: inflict.v1.entities.Return
	(*entities.Wealth)(nil),       // 9: inflict.v1.entities.Wealth
	(*entities.Worth)(nil),        // 10: inflict.v1.entities.Worth
}
var file_protos_v1_api_api_proto_depIdxs = []int32{
	0,  // 0: inflict.v1.api.Request.entity:type_name -> inflict.v1.api.Request.Type
	6,  // 1: inflict.v1.api.Request.amount:type_name -> inflict.v1.entities.Amount
	7,  // 2: inflict.v1.api.Request.maintainance:type_name -> inflict.v1.entities.Maintainance
	8,  // 3: inflict.v1.api.Request.return:type_name -> inflict.v1.entities.Return
	9,  // 4: inflict.v1.api.Request.wealth:type_name -> inflict.v1.entities.Wealth
	10, // 5: inflict.v1.api.Request.worth:type_name -> inflict.v1.entities.Worth
	4,  // 6: inflict.v1.api.Response.status:type_name -> inflict.v1.api.Status
	6,  // 7: inflict.v1.api.Response.amount:type_name -> inflict.v1.entities.Amount
	7,  // 8: inflict.v1.api.Response.maintainance:type_name -> inflict.v1.entities.Maintainance
	8,  // 9: inflict.v1.api.Response.return:type_name -> inflict.v1.entities.Return
	9,  // 10: inflict.v1.api.Response.wealth:type_name -> inflict.v1.entities.Wealth
	10, // 11: inflict.v1.api.Response.worth:type_name -> inflict.v1.entities.Worth
	1,  // 12: inflict.v1.api.Status.code:type_name -> inflict.v1.api.Status.Code
	5,  // 13: inflict.v1.api.Status.message:type_name -> inflict.v1.api.Error
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_protos_v1_api_api_proto_init() }
func file_protos_v1_api_api_proto_init() {
	if File_protos_v1_api_api_proto != nil {
		return
	}
	file_protos_v1_api_api_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_Amount)(nil),
		(*Request_Maintainance)(nil),
		(*Request_Return)(nil),
		(*Request_Wealth)(nil),
		(*Request_Worth)(nil),
	}
	file_protos_v1_api_api_proto_msgTypes[1].OneofWrappers = []any{
		(*Response_Amount)(nil),
		(*Response_Maintainance)(nil),
		(*Response_Return)(nil),
		(*Response_Wealth)(nil),
		(*Response_Worth)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_v1_api_api_proto_rawDesc), len(file_protos_v1_api_api_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_v1_api_api_proto_goTypes,
		DependencyIndexes: file_protos_v1_api_api_proto_depIdxs,
		EnumInfos:         file_protos_v1_api_api_proto_enumTypes,
		MessageInfos:      file_protos_v1_api_api_proto_msgTypes,
	}.Build()
	File_protos_v1_api_api_proto = out.File
	file_protos_v1_api_api_proto_goTypes = nil
	file_protos_v1_api_api_proto_depIdxs = nil
}
