// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protos/v1/entities/accomodation.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Accomodation_Type int32

const (
	Accomodation_TYPE_UNSPECIFIED Accomodation_Type = 0
	Accomodation_TYPE_OWNED       Accomodation_Type = 1
	Accomodation_TYPE_LEASED      Accomodation_Type = 2
	Accomodation_TYPE_RENTED      Accomodation_Type = 3
	Accomodation_TYPE_SHARED      Accomodation_Type = 4
)

// Enum value maps for Accomodation_Type.
var (
	Accomodation_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_OWNED",
		2: "TYPE_LEASED",
		3: "TYPE_RENTED",
		4: "TYPE_SHARED",
	}
	Accomodation_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_OWNED":       1,
		"TYPE_LEASED":      2,
		"TYPE_RENTED":      3,
		"TYPE_SHARED":      4,
	}
)

func (x Accomodation_Type) Enum() *Accomodation_Type {
	p := new(Accomodation_Type)
	*p = x
	return p
}

func (x Accomodation_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Accomodation_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_v1_entities_accomodation_proto_enumTypes[0].Descriptor()
}

func (Accomodation_Type) Type() protoreflect.EnumType {
	return &file_protos_v1_entities_accomodation_proto_enumTypes[0]
}

func (x Accomodation_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Accomodation_Type.Descriptor instead.
func (Accomodation_Type) EnumDescriptor() ([]byte, []int) {
	return file_protos_v1_entities_accomodation_proto_rawDescGZIP(), []int{0, 0}
}

type Accomodation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          Accomodation_Type      `protobuf:"varint,2,opt,name=type,proto3,enum=inflict.v1.entities.Accomodation_Type" json:"type,omitempty"`
	Cost          *Cost                  `protobuf:"bytes,3,opt,name=cost,proto3" json:"cost,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Accomodation) Reset() {
	*x = Accomodation{}
	mi := &file_protos_v1_entities_accomodation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accomodation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accomodation) ProtoMessage() {}

func (x *Accomodation) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_entities_accomodation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accomodation.ProtoReflect.Descriptor instead.
func (*Accomodation) Descriptor() ([]byte, []int) {
	return file_protos_v1_entities_accomodation_proto_rawDescGZIP(), []int{0}
}

func (x *Accomodation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Accomodation) GetType() Accomodation_Type {
	if x != nil {
		return x.Type
	}
	return Accomodation_TYPE_UNSPECIFIED
}

func (x *Accomodation) GetCost() *Cost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *Accomodation) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_protos_v1_entities_accomodation_proto protoreflect.FileDescriptor

const file_protos_v1_entities_accomodation_proto_rawDesc = "" +
	"\n" +
	"%protos/v1/entities/accomodation.proto\x12\x13inflict.v1.entities\x1a\x1dprotos/v1/entities/cost.proto\"\x84\x02\n" +
	"\fAccomodation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12:\n" +
	"\x04type\x18\x02 \x01(\x0e2&.inflict.v1.entities.Accomodation.TypeR\x04type\x12-\n" +
	"\x04cost\x18\x03 \x01(\v2\x19.inflict.v1.entities.CostR\x04cost\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\"_\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"TYPE_OWNED\x10\x01\x12\x0f\n" +
	"\vTYPE_LEASED\x10\x02\x12\x0f\n" +
	"\vTYPE_RENTED\x10\x03\x12\x0f\n" +
	"\vTYPE_SHARED\x10\x04B\xc8\x01\n" +
	"\x17com.inflict.v1.entitiesB\x11AccomodationProtoP\x01Z,go.ssnk.in/inflict/schema/protos/v1/entities\xa2\x02\x03IVE\xaa\x02\x13Inflict.V1.Entities\xca\x02\x13Inflict\\V1\\Entities\xe2\x02\x1fInflict\\V1\\Entities\\GPBMetadata\xea\x02\x15Inflict::V1::Entitiesb\x06proto3"

var (
	file_protos_v1_entities_accomodation_proto_rawDescOnce sync.Once
	file_protos_v1_entities_accomodation_proto_rawDescData []byte
)

func file_protos_v1_entities_accomodation_proto_rawDescGZIP() []byte {
	file_protos_v1_entities_accomodation_proto_rawDescOnce.Do(func() {
		file_protos_v1_entities_accomodation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_v1_entities_accomodation_proto_rawDesc), len(file_protos_v1_entities_accomodation_proto_rawDesc)))
	})
	return file_protos_v1_entities_accomodation_proto_rawDescData
}

var file_protos_v1_entities_accomodation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_v1_entities_accomodation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_v1_entities_accomodation_proto_goTypes = []any{
	(Accomodation_Type)(0), // 0: inflict.v1.entities.Accomodation.Type
	(*Accomodation)(nil),   // 1: inflict.v1.entities.Accomodation
	(*Cost)(nil),           // 2: inflict.v1.entities.Cost
}
var file_protos_v1_entities_accomodation_proto_depIdxs = []int32{
	0, // 0: inflict.v1.entities.Accomodation.type:type_name -> inflict.v1.entities.Accomodation.Type
	2, // 1: inflict.v1.entities.Accomodation.cost:type_name -> inflict.v1.entities.Cost
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_v1_entities_accomodation_proto_init() }
func file_protos_v1_entities_accomodation_proto_init() {
	if File_protos_v1_entities_accomodation_proto != nil {
		return
	}
	file_protos_v1_entities_cost_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_v1_entities_accomodation_proto_rawDesc), len(file_protos_v1_entities_accomodation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_v1_entities_accomodation_proto_goTypes,
		DependencyIndexes: file_protos_v1_entities_accomodation_proto_depIdxs,
		EnumInfos:         file_protos_v1_entities_accomodation_proto_enumTypes,
		MessageInfos:      file_protos_v1_entities_accomodation_proto_msgTypes,
	}.Build()
	File_protos_v1_entities_accomodation_proto = out.File
	file_protos_v1_entities_accomodation_proto_goTypes = nil
	file_protos_v1_entities_accomodation_proto_depIdxs = nil
}
