// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protos/v1/entities/amount.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Amount_Type int32

const (
	Amount_TYPE_UNSPECIFIED Amount_Type = 0
	Amount_TYPE_CREDIT      Amount_Type = 1
	Amount_TYPE_DEBIT       Amount_Type = 2
)

// Enum value maps for Amount_Type.
var (
	Amount_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_CREDIT",
		2: "TYPE_DEBIT",
	}
	Amount_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_CREDIT":      1,
		"TYPE_DEBIT":       2,
	}
)

func (x Amount_Type) Enum() *Amount_Type {
	p := new(Amount_Type)
	*p = x
	return p
}

func (x Amount_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Amount_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_v1_entities_amount_proto_enumTypes[0].Descriptor()
}

func (Amount_Type) Type() protoreflect.EnumType {
	return &file_protos_v1_entities_amount_proto_enumTypes[0]
}

func (x Amount_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Amount_Type.Descriptor instead.
func (Amount_Type) EnumDescriptor() ([]byte, []int) {
	return file_protos_v1_entities_amount_proto_rawDescGZIP(), []int{0, 0}
}

// Ideate Fixed, Variable, Recurring & OneTime amounts
type Amount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          Amount_Type            `protobuf:"varint,2,opt,name=type,proto3,enum=inflict.v1.entities.Amount_Type" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Sender        string                 `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,5,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Value         int64                  `protobuf:"varint,6,opt,name=value,proto3" json:"value,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Deleted       bool                   `protobuf:"varint,8,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amount) Reset() {
	*x = Amount{}
	mi := &file_protos_v1_entities_amount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_entities_amount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_protos_v1_entities_amount_proto_rawDescGZIP(), []int{0}
}

func (x *Amount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Amount) GetType() Amount_Type {
	if x != nil {
		return x.Type
	}
	return Amount_TYPE_UNSPECIFIED
}

func (x *Amount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Amount) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Amount) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Amount) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Amount) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Amount) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_protos_v1_entities_amount_proto protoreflect.FileDescriptor

const file_protos_v1_entities_amount_proto_rawDesc = "" +
	"\n" +
	"\x1fprotos/v1/entities/amount.proto\x12\x13inflict.v1.entities\"\xa1\x02\n" +
	"\x06Amount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x04type\x18\x02 \x01(\x0e2 .inflict.v1.entities.Amount.TypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x05 \x01(\tR\breceiver\x12\x14\n" +
	"\x05value\x18\x06 \x01(\x03R\x05value\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x18\n" +
	"\adeleted\x18\b \x01(\bR\adeleted\"=\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vTYPE_CREDIT\x10\x01\x12\x0e\n" +
	"\n" +
	"TYPE_DEBIT\x10\x02B\xc2\x01\n" +
	"\x17com.inflict.v1.entitiesB\vAmountProtoP\x01Z,go.ssnk.in/inflict/schema/protos/v1/entities\xa2\x02\x03IVE\xaa\x02\x13Inflict.V1.Entities\xca\x02\x13Inflict\\V1\\Entities\xe2\x02\x1fInflict\\V1\\Entities\\GPBMetadata\xea\x02\x15Inflict::V1::Entitiesb\x06proto3"

var (
	file_protos_v1_entities_amount_proto_rawDescOnce sync.Once
	file_protos_v1_entities_amount_proto_rawDescData []byte
)

func file_protos_v1_entities_amount_proto_rawDescGZIP() []byte {
	file_protos_v1_entities_amount_proto_rawDescOnce.Do(func() {
		file_protos_v1_entities_amount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_v1_entities_amount_proto_rawDesc), len(file_protos_v1_entities_amount_proto_rawDesc)))
	})
	return file_protos_v1_entities_amount_proto_rawDescData
}

var file_protos_v1_entities_amount_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_v1_entities_amount_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_v1_entities_amount_proto_goTypes = []any{
	(Amount_Type)(0), // 0: inflict.v1.entities.Amount.Type
	(*Amount)(nil),   // 1: inflict.v1.entities.Amount
}
var file_protos_v1_entities_amount_proto_depIdxs = []int32{
	0, // 0: inflict.v1.entities.Amount.type:type_name -> inflict.v1.entities.Amount.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_v1_entities_amount_proto_init() }
func file_protos_v1_entities_amount_proto_init() {
	if File_protos_v1_entities_amount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_v1_entities_amount_proto_rawDesc), len(file_protos_v1_entities_amount_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_v1_entities_amount_proto_goTypes,
		DependencyIndexes: file_protos_v1_entities_amount_proto_depIdxs,
		EnumInfos:         file_protos_v1_entities_amount_proto_enumTypes,
		MessageInfos:      file_protos_v1_entities_amount_proto_msgTypes,
	}.Build()
	File_protos_v1_entities_amount_proto = out.File
	file_protos_v1_entities_amount_proto_goTypes = nil
	file_protos_v1_entities_amount_proto_depIdxs = nil
}
