// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: protos/v1/entities/common.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AmountT int32

const (
	AmountT_Credit AmountT = 0
	AmountT_Debit  AmountT = 1
)

// Enum value maps for AmountT.
var (
	AmountT_name = map[int32]string{
		0: "Credit",
		1: "Debit",
	}
	AmountT_value = map[string]int32{
		"Credit": 0,
		"Debit":  1,
	}
)

func (x AmountT) Enum() *AmountT {
	p := new(AmountT)
	*p = x
	return p
}

func (x AmountT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AmountT) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_v1_entities_common_proto_enumTypes[0].Descriptor()
}

func (AmountT) Type() protoreflect.EnumType {
	return &file_protos_v1_entities_common_proto_enumTypes[0]
}

func (x AmountT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AmountT.Descriptor instead.
func (AmountT) EnumDescriptor() ([]byte, []int) {
	return file_protos_v1_entities_common_proto_rawDescGZIP(), []int{0}
}

type RateT int32

const (
	RateT_BASIS_POINTS RateT = 0
	RateT_PERCENTAGE   RateT = 1
)

// Enum value maps for RateT.
var (
	RateT_name = map[int32]string{
		0: "BASIS_POINTS",
		1: "PERCENTAGE",
	}
	RateT_value = map[string]int32{
		"BASIS_POINTS": 0,
		"PERCENTAGE":   1,
	}
)

func (x RateT) Enum() *RateT {
	p := new(RateT)
	*p = x
	return p
}

func (x RateT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RateT) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_v1_entities_common_proto_enumTypes[1].Descriptor()
}

func (RateT) Type() protoreflect.EnumType {
	return &file_protos_v1_entities_common_proto_enumTypes[1]
}

func (x RateT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RateT.Descriptor instead.
func (RateT) EnumDescriptor() ([]byte, []int) {
	return file_protos_v1_entities_common_proto_rawDescGZIP(), []int{1}
}

type AccomodationT int32

const (
	AccomodationT_Owned  AccomodationT = 0
	AccomodationT_Leased AccomodationT = 1
	AccomodationT_Rented AccomodationT = 2
	AccomodationT_Shared AccomodationT = 3
)

// Enum value maps for AccomodationT.
var (
	AccomodationT_name = map[int32]string{
		0: "Owned",
		1: "Leased",
		2: "Rented",
		3: "Shared",
	}
	AccomodationT_value = map[string]int32{
		"Owned":  0,
		"Leased": 1,
		"Rented": 2,
		"Shared": 3,
	}
)

func (x AccomodationT) Enum() *AccomodationT {
	p := new(AccomodationT)
	*p = x
	return p
}

func (x AccomodationT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccomodationT) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_v1_entities_common_proto_enumTypes[2].Descriptor()
}

func (AccomodationT) Type() protoreflect.EnumType {
	return &file_protos_v1_entities_common_proto_enumTypes[2]
}

func (x AccomodationT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccomodationT.Descriptor instead.
func (AccomodationT) EnumDescriptor() ([]byte, []int) {
	return file_protos_v1_entities_common_proto_rawDescGZIP(), []int{2}
}

// Ideate Fixed, Variable, Recurring & OneTime amounts
type Amount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          AmountT                `protobuf:"varint,2,opt,name=type,proto3,enum=inflict.v1.entities.AmountT" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Sender        string                 `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,5,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Value         int64                  `protobuf:"varint,6,opt,name=value,proto3" json:"value,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Deleted       bool                   `protobuf:"varint,8,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amount) Reset() {
	*x = Amount{}
	mi := &file_protos_v1_entities_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_entities_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_protos_v1_entities_common_proto_rawDescGZIP(), []int{0}
}

func (x *Amount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Amount) GetType() AmountT {
	if x != nil {
		return x.Type
	}
	return AmountT_Credit
}

func (x *Amount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Amount) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Amount) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Amount) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Amount) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Amount) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type Rate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          RateT                  `protobuf:"varint,1,opt,name=type,proto3,enum=inflict.v1.entities.RateT" json:"type,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rate) Reset() {
	*x = Rate{}
	mi := &file_protos_v1_entities_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rate) ProtoMessage() {}

func (x *Rate) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_entities_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rate.ProtoReflect.Descriptor instead.
func (*Rate) Descriptor() ([]byte, []int) {
	return file_protos_v1_entities_common_proto_rawDescGZIP(), []int{1}
}

func (x *Rate) GetType() RateT {
	if x != nil {
		return x.Type
	}
	return RateT_BASIS_POINTS
}

func (x *Rate) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Maintainance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Cost          *Amount                `protobuf:"bytes,3,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Maintainance) Reset() {
	*x = Maintainance{}
	mi := &file_protos_v1_entities_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Maintainance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Maintainance) ProtoMessage() {}

func (x *Maintainance) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_entities_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Maintainance.ProtoReflect.Descriptor instead.
func (*Maintainance) Descriptor() ([]byte, []int) {
	return file_protos_v1_entities_common_proto_rawDescGZIP(), []int{2}
}

func (x *Maintainance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Maintainance) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Maintainance) GetCost() *Amount {
	if x != nil {
		return x.Cost
	}
	return nil
}

type Cost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        *Amount                `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Maintainance  *Maintainance          `protobuf:"bytes,3,opt,name=maintainance,proto3" json:"maintainance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cost) Reset() {
	*x = Cost{}
	mi := &file_protos_v1_entities_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cost) ProtoMessage() {}

func (x *Cost) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_entities_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cost.ProtoReflect.Descriptor instead.
func (*Cost) Descriptor() ([]byte, []int) {
	return file_protos_v1_entities_common_proto_rawDescGZIP(), []int{3}
}

func (x *Cost) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cost) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Cost) GetMaintainance() *Maintainance {
	if x != nil {
		return x.Maintainance
	}
	return nil
}

type Accomodation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          AccomodationT          `protobuf:"varint,2,opt,name=type,proto3,enum=inflict.v1.entities.AccomodationT" json:"type,omitempty"`
	Cost          *Cost                  `protobuf:"bytes,3,opt,name=cost,proto3" json:"cost,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Accomodation) Reset() {
	*x = Accomodation{}
	mi := &file_protos_v1_entities_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accomodation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accomodation) ProtoMessage() {}

func (x *Accomodation) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_entities_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accomodation.ProtoReflect.Descriptor instead.
func (*Accomodation) Descriptor() ([]byte, []int) {
	return file_protos_v1_entities_common_proto_rawDescGZIP(), []int{4}
}

func (x *Accomodation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Accomodation) GetType() AccomodationT {
	if x != nil {
		return x.Type
	}
	return AccomodationT_Owned
}

func (x *Accomodation) GetCost() *Cost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *Accomodation) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_protos_v1_entities_common_proto protoreflect.FileDescriptor

const file_protos_v1_entities_common_proto_rawDesc = "" +
	"\n" +
	"\x1fprotos/v1/entities/common.proto\x12\x13inflict.v1.entities\"\xde\x01\n" +
	"\x06Amount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.inflict.v1.entities.AmountTR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x05 \x01(\tR\breceiver\x12\x14\n" +
	"\x05value\x18\x06 \x01(\x03R\x05value\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x18\n" +
	"\adeleted\x18\b \x01(\bR\adeleted\"L\n" +
	"\x04Rate\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.inflict.v1.entities.RateTR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"c\n" +
	"\fMaintainance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12/\n" +
	"\x04cost\x18\x03 \x01(\v2\x1b.inflict.v1.entities.AmountR\x04cost\"\x92\x01\n" +
	"\x04Cost\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\x06amount\x18\x02 \x01(\v2\x1b.inflict.v1.entities.AmountR\x06amount\x12E\n" +
	"\fmaintainance\x18\x03 \x01(\v2!.inflict.v1.entities.MaintainanceR\fmaintainance\"\x9f\x01\n" +
	"\fAccomodation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x04type\x18\x02 \x01(\x0e2\".inflict.v1.entities.AccomodationTR\x04type\x12-\n" +
	"\x04cost\x18\x03 \x01(\v2\x19.inflict.v1.entities.CostR\x04cost\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress* \n" +
	"\aAmountT\x12\n" +
	"\n" +
	"\x06Credit\x10\x00\x12\t\n" +
	"\x05Debit\x10\x01*)\n" +
	"\x05RateT\x12\x10\n" +
	"\fBASIS_POINTS\x10\x00\x12\x0e\n" +
	"\n" +
	"PERCENTAGE\x10\x01*>\n" +
	"\rAccomodationT\x12\t\n" +
	"\x05Owned\x10\x00\x12\n" +
	"\n" +
	"\x06Leased\x10\x01\x12\n" +
	"\n" +
	"\x06Rented\x10\x02\x12\n" +
	"\n" +
	"\x06Shared\x10\x03B\xc2\x01\n" +
	"\x17com.inflict.v1.entitiesB\vCommonProtoP\x01Z,go.ssnk.in/inflict/schema/protos/v1/entities\xa2\x02\x03IVE\xaa\x02\x13Inflict.V1.Entities\xca\x02\x13Inflict\\V1\\Entities\xe2\x02\x1fInflict\\V1\\Entities\\GPBMetadata\xea\x02\x15Inflict::V1::Entitiesb\x06proto3"

var (
	file_protos_v1_entities_common_proto_rawDescOnce sync.Once
	file_protos_v1_entities_common_proto_rawDescData []byte
)

func file_protos_v1_entities_common_proto_rawDescGZIP() []byte {
	file_protos_v1_entities_common_proto_rawDescOnce.Do(func() {
		file_protos_v1_entities_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_v1_entities_common_proto_rawDesc), len(file_protos_v1_entities_common_proto_rawDesc)))
	})
	return file_protos_v1_entities_common_proto_rawDescData
}

var file_protos_v1_entities_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protos_v1_entities_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_v1_entities_common_proto_goTypes = []any{
	(AmountT)(0),         // 0: inflict.v1.entities.AmountT
	(RateT)(0),           // 1: inflict.v1.entities.RateT
	(AccomodationT)(0),   // 2: inflict.v1.entities.AccomodationT
	(*Amount)(nil),       // 3: inflict.v1.entities.Amount
	(*Rate)(nil),         // 4: inflict.v1.entities.Rate
	(*Maintainance)(nil), // 5: inflict.v1.entities.Maintainance
	(*Cost)(nil),         // 6: inflict.v1.entities.Cost
	(*Accomodation)(nil), // 7: inflict.v1.entities.Accomodation
}
var file_protos_v1_entities_common_proto_depIdxs = []int32{
	0, // 0: inflict.v1.entities.Amount.type:type_name -> inflict.v1.entities.AmountT
	1, // 1: inflict.v1.entities.Rate.type:type_name -> inflict.v1.entities.RateT
	3, // 2: inflict.v1.entities.Maintainance.cost:type_name -> inflict.v1.entities.Amount
	3, // 3: inflict.v1.entities.Cost.amount:type_name -> inflict.v1.entities.Amount
	5, // 4: inflict.v1.entities.Cost.maintainance:type_name -> inflict.v1.entities.Maintainance
	2, // 5: inflict.v1.entities.Accomodation.type:type_name -> inflict.v1.entities.AccomodationT
	6, // 6: inflict.v1.entities.Accomodation.cost:type_name -> inflict.v1.entities.Cost
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_protos_v1_entities_common_proto_init() }
func file_protos_v1_entities_common_proto_init() {
	if File_protos_v1_entities_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_v1_entities_common_proto_rawDesc), len(file_protos_v1_entities_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_v1_entities_common_proto_goTypes,
		DependencyIndexes: file_protos_v1_entities_common_proto_depIdxs,
		EnumInfos:         file_protos_v1_entities_common_proto_enumTypes,
		MessageInfos:      file_protos_v1_entities_common_proto_msgTypes,
	}.Build()
	File_protos_v1_entities_common_proto = out.File
	file_protos_v1_entities_common_proto_goTypes = nil
	file_protos_v1_entities_common_proto_depIdxs = nil
}
