// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protos/v1/entities/cost.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        *Amount                `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Maintainance  *Maintainance          `protobuf:"bytes,3,opt,name=maintainance,proto3" json:"maintainance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cost) Reset() {
	*x = Cost{}
	mi := &file_protos_v1_entities_cost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cost) ProtoMessage() {}

func (x *Cost) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_entities_cost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cost.ProtoReflect.Descriptor instead.
func (*Cost) Descriptor() ([]byte, []int) {
	return file_protos_v1_entities_cost_proto_rawDescGZIP(), []int{0}
}

func (x *Cost) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cost) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Cost) GetMaintainance() *Maintainance {
	if x != nil {
		return x.Maintainance
	}
	return nil
}

var File_protos_v1_entities_cost_proto protoreflect.FileDescriptor

const file_protos_v1_entities_cost_proto_rawDesc = "" +
	"\n" +
	"\x1dprotos/v1/entities/cost.proto\x12\x13inflict.v1.entities\x1a\x1fprotos/v1/entities/amount.proto\x1a%protos/v1/entities/maintainance.proto\"\x92\x01\n" +
	"\x04Cost\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\x06amount\x18\x02 \x01(\v2\x1b.inflict.v1.entities.AmountR\x06amount\x12E\n" +
	"\fmaintainance\x18\x03 \x01(\v2!.inflict.v1.entities.MaintainanceR\fmaintainanceB\xc0\x01\n" +
	"\x17com.inflict.v1.entitiesB\tCostProtoP\x01Z,go.ssnk.in/inflict/schema/protos/v1/entities\xa2\x02\x03IVE\xaa\x02\x13Inflict.V1.Entities\xca\x02\x13Inflict\\V1\\Entities\xe2\x02\x1fInflict\\V1\\Entities\\GPBMetadata\xea\x02\x15Inflict::V1::Entitiesb\x06proto3"

var (
	file_protos_v1_entities_cost_proto_rawDescOnce sync.Once
	file_protos_v1_entities_cost_proto_rawDescData []byte
)

func file_protos_v1_entities_cost_proto_rawDescGZIP() []byte {
	file_protos_v1_entities_cost_proto_rawDescOnce.Do(func() {
		file_protos_v1_entities_cost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_v1_entities_cost_proto_rawDesc), len(file_protos_v1_entities_cost_proto_rawDesc)))
	})
	return file_protos_v1_entities_cost_proto_rawDescData
}

var file_protos_v1_entities_cost_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_v1_entities_cost_proto_goTypes = []any{
	(*Cost)(nil),         // 0: inflict.v1.entities.Cost
	(*Amount)(nil),       // 1: inflict.v1.entities.Amount
	(*Maintainance)(nil), // 2: inflict.v1.entities.Maintainance
}
var file_protos_v1_entities_cost_proto_depIdxs = []int32{
	1, // 0: inflict.v1.entities.Cost.amount:type_name -> inflict.v1.entities.Amount
	2, // 1: inflict.v1.entities.Cost.maintainance:type_name -> inflict.v1.entities.Maintainance
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_v1_entities_cost_proto_init() }
func file_protos_v1_entities_cost_proto_init() {
	if File_protos_v1_entities_cost_proto != nil {
		return
	}
	file_protos_v1_entities_amount_proto_init()
	file_protos_v1_entities_maintainance_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_v1_entities_cost_proto_rawDesc), len(file_protos_v1_entities_cost_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_v1_entities_cost_proto_goTypes,
		DependencyIndexes: file_protos_v1_entities_cost_proto_depIdxs,
		MessageInfos:      file_protos_v1_entities_cost_proto_msgTypes,
	}.Build()
	File_protos_v1_entities_cost_proto = out.File
	file_protos_v1_entities_cost_proto_goTypes = nil
	file_protos_v1_entities_cost_proto_depIdxs = nil
}
