// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: protos/v1/entities/entity.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Accomodations []*Accomodation        `protobuf:"bytes,3,rep,name=accomodations,proto3" json:"accomodations,omitempty"`
	Members       []*Member              `protobuf:"bytes,4,rep,name=members,proto3" json:"members,omitempty"`
	Community     []*Family              `protobuf:"bytes,5,rep,name=community,proto3" json:"community,omitempty"`
	NetWorth      *Worth                 `protobuf:"bytes,6,opt,name=net_worth,json=netWorth,proto3" json:"net_worth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_protos_v1_entities_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_entities_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_protos_v1_entities_entity_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entity) GetAccomodations() []*Accomodation {
	if x != nil {
		return x.Accomodations
	}
	return nil
}

func (x *Entity) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Entity) GetCommunity() []*Family {
	if x != nil {
		return x.Community
	}
	return nil
}

func (x *Entity) GetNetWorth() *Worth {
	if x != nil {
		return x.NetWorth
	}
	return nil
}

var File_protos_v1_entities_entity_proto protoreflect.FileDescriptor

const file_protos_v1_entities_entity_proto_rawDesc = "" +
	"\n" +
	"\x1fprotos/v1/entities/entity.proto\x12\x13inflict.v1.entities\x1a\x1fprotos/v1/entities/common.proto\x1a\x1fprotos/v1/entities/wealth.proto\x1a\x1fprotos/v1/entities/member.proto\x1a\x1fprotos/v1/entities/family.proto\"\xa0\x02\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12G\n" +
	"\raccomodations\x18\x03 \x03(\v2!.inflict.v1.entities.AccomodationR\raccomodations\x125\n" +
	"\amembers\x18\x04 \x03(\v2\x1b.inflict.v1.entities.MemberR\amembers\x129\n" +
	"\tcommunity\x18\x05 \x03(\v2\x1b.inflict.v1.entities.FamilyR\tcommunity\x127\n" +
	"\tnet_worth\x18\x06 \x01(\v2\x1a.inflict.v1.entities.WorthR\bnetWorthB\xc2\x01\n" +
	"\x17com.inflict.v1.entitiesB\vEntityProtoP\x01Z,go.ssnk.in/inflict/schema/protos/v1/entities\xa2\x02\x03IVE\xaa\x02\x13Inflict.V1.Entities\xca\x02\x13Inflict\\V1\\Entities\xe2\x02\x1fInflict\\V1\\Entities\\GPBMetadata\xea\x02\x15Inflict::V1::Entitiesb\x06proto3"

var (
	file_protos_v1_entities_entity_proto_rawDescOnce sync.Once
	file_protos_v1_entities_entity_proto_rawDescData []byte
)

func file_protos_v1_entities_entity_proto_rawDescGZIP() []byte {
	file_protos_v1_entities_entity_proto_rawDescOnce.Do(func() {
		file_protos_v1_entities_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_v1_entities_entity_proto_rawDesc), len(file_protos_v1_entities_entity_proto_rawDesc)))
	})
	return file_protos_v1_entities_entity_proto_rawDescData
}

var file_protos_v1_entities_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_v1_entities_entity_proto_goTypes = []any{
	(*Entity)(nil),       // 0: inflict.v1.entities.Entity
	(*Accomodation)(nil), // 1: inflict.v1.entities.Accomodation
	(*Member)(nil),       // 2: inflict.v1.entities.Member
	(*Family)(nil),       // 3: inflict.v1.entities.Family
	(*Worth)(nil),        // 4: inflict.v1.entities.Worth
}
var file_protos_v1_entities_entity_proto_depIdxs = []int32{
	1, // 0: inflict.v1.entities.Entity.accomodations:type_name -> inflict.v1.entities.Accomodation
	2, // 1: inflict.v1.entities.Entity.members:type_name -> inflict.v1.entities.Member
	3, // 2: inflict.v1.entities.Entity.community:type_name -> inflict.v1.entities.Family
	4, // 3: inflict.v1.entities.Entity.net_worth:type_name -> inflict.v1.entities.Worth
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protos_v1_entities_entity_proto_init() }
func file_protos_v1_entities_entity_proto_init() {
	if File_protos_v1_entities_entity_proto != nil {
		return
	}
	file_protos_v1_entities_common_proto_init()
	file_protos_v1_entities_wealth_proto_init()
	file_protos_v1_entities_member_proto_init()
	file_protos_v1_entities_family_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_v1_entities_entity_proto_rawDesc), len(file_protos_v1_entities_entity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_v1_entities_entity_proto_goTypes,
		DependencyIndexes: file_protos_v1_entities_entity_proto_depIdxs,
		MessageInfos:      file_protos_v1_entities_entity_proto_msgTypes,
	}.Build()
	File_protos_v1_entities_entity_proto = out.File
	file_protos_v1_entities_entity_proto_goTypes = nil
	file_protos_v1_entities_entity_proto_depIdxs = nil
}
