// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: protos/v1/entities/family.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FamilyT int32

const (
	FamilyT_Nuclear FamilyT = 0
	FamilyT_Joint   FamilyT = 1
)

// Enum value maps for FamilyT.
var (
	FamilyT_name = map[int32]string{
		0: "Nuclear",
		1: "Joint",
	}
	FamilyT_value = map[string]int32{
		"Nuclear": 0,
		"Joint":   1,
	}
)

func (x FamilyT) Enum() *FamilyT {
	p := new(FamilyT)
	*p = x
	return p
}

func (x FamilyT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FamilyT) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_v1_entities_family_proto_enumTypes[0].Descriptor()
}

func (FamilyT) Type() protoreflect.EnumType {
	return &file_protos_v1_entities_family_proto_enumTypes[0]
}

func (x FamilyT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FamilyT.Descriptor instead.
func (FamilyT) EnumDescriptor() ([]byte, []int) {
	return file_protos_v1_entities_family_proto_rawDescGZIP(), []int{0}
}

type Family struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          FamilyT                `protobuf:"varint,3,opt,name=type,proto3,enum=inflict.v1.entities.FamilyT" json:"type,omitempty"`
	Members       []*Member              `protobuf:"bytes,4,rep,name=members,proto3" json:"members,omitempty"`
	Accomodations []*Accomodation        `protobuf:"bytes,5,rep,name=accomodations,proto3" json:"accomodations,omitempty"`
	NetWorth      *Worth                 `protobuf:"bytes,6,opt,name=net_worth,json=netWorth,proto3" json:"net_worth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Family) Reset() {
	*x = Family{}
	mi := &file_protos_v1_entities_family_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Family) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Family) ProtoMessage() {}

func (x *Family) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_entities_family_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Family.ProtoReflect.Descriptor instead.
func (*Family) Descriptor() ([]byte, []int) {
	return file_protos_v1_entities_family_proto_rawDescGZIP(), []int{0}
}

func (x *Family) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Family) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Family) GetType() FamilyT {
	if x != nil {
		return x.Type
	}
	return FamilyT_Nuclear
}

func (x *Family) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Family) GetAccomodations() []*Accomodation {
	if x != nil {
		return x.Accomodations
	}
	return nil
}

func (x *Family) GetNetWorth() *Worth {
	if x != nil {
		return x.NetWorth
	}
	return nil
}

var File_protos_v1_entities_family_proto protoreflect.FileDescriptor

const file_protos_v1_entities_family_proto_rawDesc = "" +
	"\n" +
	"\x1fprotos/v1/entities/family.proto\x12\x13inflict.v1.entities\x1a\x1fprotos/v1/entities/common.proto\x1a\x1fprotos/v1/entities/member.proto\x1a\x1fprotos/v1/entities/wealth.proto\"\x97\x02\n" +
	"\x06Family\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x120\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1c.inflict.v1.entities.FamilyTR\x04type\x125\n" +
	"\amembers\x18\x04 \x03(\v2\x1b.inflict.v1.entities.MemberR\amembers\x12G\n" +
	"\raccomodations\x18\x05 \x03(\v2!.inflict.v1.entities.AccomodationR\raccomodations\x127\n" +
	"\tnet_worth\x18\x06 \x01(\v2\x1a.inflict.v1.entities.WorthR\bnetWorth*!\n" +
	"\aFamilyT\x12\v\n" +
	"\aNuclear\x10\x00\x12\t\n" +
	"\x05Joint\x10\x01B\xc2\x01\n" +
	"\x17com.inflict.v1.entitiesB\vFamilyProtoP\x01Z,go.ssnk.in/inflict/schema/protos/v1/entities\xa2\x02\x03IVE\xaa\x02\x13Inflict.V1.Entities\xca\x02\x13Inflict\\V1\\Entities\xe2\x02\x1fInflict\\V1\\Entities\\GPBMetadata\xea\x02\x15Inflict::V1::Entitiesb\x06proto3"

var (
	file_protos_v1_entities_family_proto_rawDescOnce sync.Once
	file_protos_v1_entities_family_proto_rawDescData []byte
)

func file_protos_v1_entities_family_proto_rawDescGZIP() []byte {
	file_protos_v1_entities_family_proto_rawDescOnce.Do(func() {
		file_protos_v1_entities_family_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_v1_entities_family_proto_rawDesc), len(file_protos_v1_entities_family_proto_rawDesc)))
	})
	return file_protos_v1_entities_family_proto_rawDescData
}

var file_protos_v1_entities_family_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_v1_entities_family_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_v1_entities_family_proto_goTypes = []any{
	(FamilyT)(0),         // 0: inflict.v1.entities.FamilyT
	(*Family)(nil),       // 1: inflict.v1.entities.Family
	(*Member)(nil),       // 2: inflict.v1.entities.Member
	(*Accomodation)(nil), // 3: inflict.v1.entities.Accomodation
	(*Worth)(nil),        // 4: inflict.v1.entities.Worth
}
var file_protos_v1_entities_family_proto_depIdxs = []int32{
	0, // 0: inflict.v1.entities.Family.type:type_name -> inflict.v1.entities.FamilyT
	2, // 1: inflict.v1.entities.Family.members:type_name -> inflict.v1.entities.Member
	3, // 2: inflict.v1.entities.Family.accomodations:type_name -> inflict.v1.entities.Accomodation
	4, // 3: inflict.v1.entities.Family.net_worth:type_name -> inflict.v1.entities.Worth
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protos_v1_entities_family_proto_init() }
func file_protos_v1_entities_family_proto_init() {
	if File_protos_v1_entities_family_proto != nil {
		return
	}
	file_protos_v1_entities_common_proto_init()
	file_protos_v1_entities_member_proto_init()
	file_protos_v1_entities_wealth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_v1_entities_family_proto_rawDesc), len(file_protos_v1_entities_family_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_v1_entities_family_proto_goTypes,
		DependencyIndexes: file_protos_v1_entities_family_proto_depIdxs,
		EnumInfos:         file_protos_v1_entities_family_proto_enumTypes,
		MessageInfos:      file_protos_v1_entities_family_proto_msgTypes,
	}.Build()
	File_protos_v1_entities_family_proto = out.File
	file_protos_v1_entities_family_proto_goTypes = nil
	file_protos_v1_entities_family_proto_depIdxs = nil
}
