// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protos/v1/entities/maintainance.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Maintainance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Cost          *Amount                `protobuf:"bytes,4,opt,name=cost,proto3" json:"cost,omitempty"`
	Deleted       bool                   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Maintainance) Reset() {
	*x = Maintainance{}
	mi := &file_protos_v1_entities_maintainance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Maintainance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Maintainance) ProtoMessage() {}

func (x *Maintainance) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_entities_maintainance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Maintainance.ProtoReflect.Descriptor instead.
func (*Maintainance) Descriptor() ([]byte, []int) {
	return file_protos_v1_entities_maintainance_proto_rawDescGZIP(), []int{0}
}

func (x *Maintainance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Maintainance) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Maintainance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Maintainance) GetCost() *Amount {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *Maintainance) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_protos_v1_entities_maintainance_proto protoreflect.FileDescriptor

const file_protos_v1_entities_maintainance_proto_rawDesc = "" +
	"\n" +
	"%protos/v1/entities/maintainance.proto\x12\x13inflict.v1.entities\x1a\x1fprotos/v1/entities/amount.proto\"\x91\x01\n" +
	"\fMaintainance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12/\n" +
	"\x04cost\x18\x04 \x01(\v2\x1b.inflict.v1.entities.AmountR\x04cost\x12\x18\n" +
	"\adeleted\x18\x05 \x01(\bR\adeletedB\xc8\x01\n" +
	"\x17com.inflict.v1.entitiesB\x11MaintainanceProtoP\x01Z,go.ssnk.in/inflict/schema/protos/v1/entities\xa2\x02\x03IVE\xaa\x02\x13Inflict.V1.Entities\xca\x02\x13Inflict\\V1\\Entities\xe2\x02\x1fInflict\\V1\\Entities\\GPBMetadata\xea\x02\x15Inflict::V1::Entitiesb\x06proto3"

var (
	file_protos_v1_entities_maintainance_proto_rawDescOnce sync.Once
	file_protos_v1_entities_maintainance_proto_rawDescData []byte
)

func file_protos_v1_entities_maintainance_proto_rawDescGZIP() []byte {
	file_protos_v1_entities_maintainance_proto_rawDescOnce.Do(func() {
		file_protos_v1_entities_maintainance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_v1_entities_maintainance_proto_rawDesc), len(file_protos_v1_entities_maintainance_proto_rawDesc)))
	})
	return file_protos_v1_entities_maintainance_proto_rawDescData
}

var file_protos_v1_entities_maintainance_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_v1_entities_maintainance_proto_goTypes = []any{
	(*Maintainance)(nil), // 0: inflict.v1.entities.Maintainance
	(*Amount)(nil),       // 1: inflict.v1.entities.Amount
}
var file_protos_v1_entities_maintainance_proto_depIdxs = []int32{
	1, // 0: inflict.v1.entities.Maintainance.cost:type_name -> inflict.v1.entities.Amount
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_v1_entities_maintainance_proto_init() }
func file_protos_v1_entities_maintainance_proto_init() {
	if File_protos_v1_entities_maintainance_proto != nil {
		return
	}
	file_protos_v1_entities_amount_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_v1_entities_maintainance_proto_rawDesc), len(file_protos_v1_entities_maintainance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_v1_entities_maintainance_proto_goTypes,
		DependencyIndexes: file_protos_v1_entities_maintainance_proto_depIdxs,
		MessageInfos:      file_protos_v1_entities_maintainance_proto_msgTypes,
	}.Build()
	File_protos_v1_entities_maintainance_proto = out.File
	file_protos_v1_entities_maintainance_proto_goTypes = nil
	file_protos_v1_entities_maintainance_proto_depIdxs = nil
}
