// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: protos/v1/entities/member.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberT int32

const (
	MemberT_Earner    MemberT = 0
	MemberT_Dependent MemberT = 1
)

// Enum value maps for MemberT.
var (
	MemberT_name = map[int32]string{
		0: "Earner",
		1: "Dependent",
	}
	MemberT_value = map[string]int32{
		"Earner":    0,
		"Dependent": 1,
	}
)

func (x MemberT) Enum() *MemberT {
	p := new(MemberT)
	*p = x
	return p
}

func (x MemberT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberT) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_v1_entities_member_proto_enumTypes[0].Descriptor()
}

func (MemberT) Type() protoreflect.EnumType {
	return &file_protos_v1_entities_member_proto_enumTypes[0]
}

func (x MemberT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberT.Descriptor instead.
func (MemberT) EnumDescriptor() ([]byte, []int) {
	return file_protos_v1_entities_member_proto_rawDescGZIP(), []int{0}
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          MemberT                `protobuf:"varint,3,opt,name=type,proto3,enum=inflict.v1.entities.MemberT" json:"type,omitempty"`
	Accomodations []*Accomodation        `protobuf:"bytes,4,rep,name=accomodations,proto3" json:"accomodations,omitempty"`
	NetWorth      *Worth                 `protobuf:"bytes,5,opt,name=net_worth,json=netWorth,proto3" json:"net_worth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_protos_v1_entities_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_entities_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_protos_v1_entities_member_proto_rawDescGZIP(), []int{0}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Member) GetType() MemberT {
	if x != nil {
		return x.Type
	}
	return MemberT_Earner
}

func (x *Member) GetAccomodations() []*Accomodation {
	if x != nil {
		return x.Accomodations
	}
	return nil
}

func (x *Member) GetNetWorth() *Worth {
	if x != nil {
		return x.NetWorth
	}
	return nil
}

var File_protos_v1_entities_member_proto protoreflect.FileDescriptor

const file_protos_v1_entities_member_proto_rawDesc = "" +
	"\n" +
	"\x1fprotos/v1/entities/member.proto\x12\x13inflict.v1.entities\x1a\x1fprotos/v1/entities/common.proto\x1a\x1fprotos/v1/entities/wealth.proto\"\xe0\x01\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x120\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1c.inflict.v1.entities.MemberTR\x04type\x12G\n" +
	"\raccomodations\x18\x04 \x03(\v2!.inflict.v1.entities.AccomodationR\raccomodations\x127\n" +
	"\tnet_worth\x18\x05 \x01(\v2\x1a.inflict.v1.entities.WorthR\bnetWorth*$\n" +
	"\aMemberT\x12\n" +
	"\n" +
	"\x06Earner\x10\x00\x12\r\n" +
	"\tDependent\x10\x01B\xc2\x01\n" +
	"\x17com.inflict.v1.entitiesB\vMemberProtoP\x01Z,go.ssnk.in/inflict/schema/protos/v1/entities\xa2\x02\x03IVE\xaa\x02\x13Inflict.V1.Entities\xca\x02\x13Inflict\\V1\\Entities\xe2\x02\x1fInflict\\V1\\Entities\\GPBMetadata\xea\x02\x15Inflict::V1::Entitiesb\x06proto3"

var (
	file_protos_v1_entities_member_proto_rawDescOnce sync.Once
	file_protos_v1_entities_member_proto_rawDescData []byte
)

func file_protos_v1_entities_member_proto_rawDescGZIP() []byte {
	file_protos_v1_entities_member_proto_rawDescOnce.Do(func() {
		file_protos_v1_entities_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_v1_entities_member_proto_rawDesc), len(file_protos_v1_entities_member_proto_rawDesc)))
	})
	return file_protos_v1_entities_member_proto_rawDescData
}

var file_protos_v1_entities_member_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_v1_entities_member_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_v1_entities_member_proto_goTypes = []any{
	(MemberT)(0),         // 0: inflict.v1.entities.MemberT
	(*Member)(nil),       // 1: inflict.v1.entities.Member
	(*Accomodation)(nil), // 2: inflict.v1.entities.Accomodation
	(*Worth)(nil),        // 3: inflict.v1.entities.Worth
}
var file_protos_v1_entities_member_proto_depIdxs = []int32{
	0, // 0: inflict.v1.entities.Member.type:type_name -> inflict.v1.entities.MemberT
	2, // 1: inflict.v1.entities.Member.accomodations:type_name -> inflict.v1.entities.Accomodation
	3, // 2: inflict.v1.entities.Member.net_worth:type_name -> inflict.v1.entities.Worth
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_v1_entities_member_proto_init() }
func file_protos_v1_entities_member_proto_init() {
	if File_protos_v1_entities_member_proto != nil {
		return
	}
	file_protos_v1_entities_common_proto_init()
	file_protos_v1_entities_wealth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_v1_entities_member_proto_rawDesc), len(file_protos_v1_entities_member_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_v1_entities_member_proto_goTypes,
		DependencyIndexes: file_protos_v1_entities_member_proto_depIdxs,
		EnumInfos:         file_protos_v1_entities_member_proto_enumTypes,
		MessageInfos:      file_protos_v1_entities_member_proto_msgTypes,
	}.Build()
	File_protos_v1_entities_member_proto = out.File
	file_protos_v1_entities_member_proto_goTypes = nil
	file_protos_v1_entities_member_proto_depIdxs = nil
}
