// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protos/v1/entities/rate.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rate_Type int32

const (
	Rate_TYPE_UNSPECIFIED  Rate_Type = 0
	Rate_TYPE_BASIS_POINTS Rate_Type = 1
	Rate_TYPE_PERCENTAGE   Rate_Type = 2
)

// Enum value maps for Rate_Type.
var (
	Rate_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_BASIS_POINTS",
		2: "TYPE_PERCENTAGE",
	}
	Rate_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":  0,
		"TYPE_BASIS_POINTS": 1,
		"TYPE_PERCENTAGE":   2,
	}
)

func (x Rate_Type) Enum() *Rate_Type {
	p := new(Rate_Type)
	*p = x
	return p
}

func (x Rate_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Rate_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_v1_entities_rate_proto_enumTypes[0].Descriptor()
}

func (Rate_Type) Type() protoreflect.EnumType {
	return &file_protos_v1_entities_rate_proto_enumTypes[0]
}

func (x Rate_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Rate_Type.Descriptor instead.
func (Rate_Type) EnumDescriptor() ([]byte, []int) {
	return file_protos_v1_entities_rate_proto_rawDescGZIP(), []int{0, 0}
}

type Rate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Rate_Type              `protobuf:"varint,2,opt,name=type,proto3,enum=inflict.v1.entities.Rate_Type" json:"type,omitempty"`
	Value         int64                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rate) Reset() {
	*x = Rate{}
	mi := &file_protos_v1_entities_rate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rate) ProtoMessage() {}

func (x *Rate) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_entities_rate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rate.ProtoReflect.Descriptor instead.
func (*Rate) Descriptor() ([]byte, []int) {
	return file_protos_v1_entities_rate_proto_rawDescGZIP(), []int{0}
}

func (x *Rate) GetType() Rate_Type {
	if x != nil {
		return x.Type
	}
	return Rate_TYPE_UNSPECIFIED
}

func (x *Rate) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_protos_v1_entities_rate_proto protoreflect.FileDescriptor

const file_protos_v1_entities_rate_proto_rawDesc = "" +
	"\n" +
	"\x1dprotos/v1/entities/rate.proto\x12\x13inflict.v1.entities\"\x9a\x01\n" +
	"\x04Rate\x122\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1e.inflict.v1.entities.Rate.TypeR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x03R\x05value\"H\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TYPE_BASIS_POINTS\x10\x01\x12\x13\n" +
	"\x0fTYPE_PERCENTAGE\x10\x02B\xc0\x01\n" +
	"\x17com.inflict.v1.entitiesB\tRateProtoP\x01Z,go.ssnk.in/inflict/schema/protos/v1/entities\xa2\x02\x03IVE\xaa\x02\x13Inflict.V1.Entities\xca\x02\x13Inflict\\V1\\Entities\xe2\x02\x1fInflict\\V1\\Entities\\GPBMetadata\xea\x02\x15Inflict::V1::Entitiesb\x06proto3"

var (
	file_protos_v1_entities_rate_proto_rawDescOnce sync.Once
	file_protos_v1_entities_rate_proto_rawDescData []byte
)

func file_protos_v1_entities_rate_proto_rawDescGZIP() []byte {
	file_protos_v1_entities_rate_proto_rawDescOnce.Do(func() {
		file_protos_v1_entities_rate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_v1_entities_rate_proto_rawDesc), len(file_protos_v1_entities_rate_proto_rawDesc)))
	})
	return file_protos_v1_entities_rate_proto_rawDescData
}

var file_protos_v1_entities_rate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_v1_entities_rate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_v1_entities_rate_proto_goTypes = []any{
	(Rate_Type)(0), // 0: inflict.v1.entities.Rate.Type
	(*Rate)(nil),   // 1: inflict.v1.entities.Rate
}
var file_protos_v1_entities_rate_proto_depIdxs = []int32{
	0, // 0: inflict.v1.entities.Rate.type:type_name -> inflict.v1.entities.Rate.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_v1_entities_rate_proto_init() }
func file_protos_v1_entities_rate_proto_init() {
	if File_protos_v1_entities_rate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_v1_entities_rate_proto_rawDesc), len(file_protos_v1_entities_rate_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_v1_entities_rate_proto_goTypes,
		DependencyIndexes: file_protos_v1_entities_rate_proto_depIdxs,
		EnumInfos:         file_protos_v1_entities_rate_proto_enumTypes,
		MessageInfos:      file_protos_v1_entities_rate_proto_msgTypes,
	}.Build()
	File_protos_v1_entities_rate_proto = out.File
	file_protos_v1_entities_rate_proto_goTypes = nil
	file_protos_v1_entities_rate_proto_depIdxs = nil
}
