// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protos/v1/entities/wealth.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Redundant because Worth is the primary table for any Entity, Member or Family, Used for development purposes
type Wealth_Type int32

const (
	Wealth_TYPE_UNSPECIFIED Wealth_Type = 0
	Wealth_TYPE_EARNING     Wealth_Type = 1
	Wealth_TYPE_EXPENSE     Wealth_Type = 2
	Wealth_TYPE_LIABILITY   Wealth_Type = 3
	Wealth_TYPE_SAVING      Wealth_Type = 4
	Wealth_TYPE_INVESTMENT  Wealth_Type = 5
	Wealth_TYPE_INSURANCE   Wealth_Type = 6
)

// Enum value maps for Wealth_Type.
var (
	Wealth_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_EARNING",
		2: "TYPE_EXPENSE",
		3: "TYPE_LIABILITY",
		4: "TYPE_SAVING",
		5: "TYPE_INVESTMENT",
		6: "TYPE_INSURANCE",
	}
	Wealth_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_EARNING":     1,
		"TYPE_EXPENSE":     2,
		"TYPE_LIABILITY":   3,
		"TYPE_SAVING":      4,
		"TYPE_INVESTMENT":  5,
		"TYPE_INSURANCE":   6,
	}
)

func (x Wealth_Type) Enum() *Wealth_Type {
	p := new(Wealth_Type)
	*p = x
	return p
}

func (x Wealth_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Wealth_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_v1_entities_wealth_proto_enumTypes[0].Descriptor()
}

func (Wealth_Type) Type() protoreflect.EnumType {
	return &file_protos_v1_entities_wealth_proto_enumTypes[0]
}

func (x Wealth_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Wealth_Type.Descriptor instead.
func (Wealth_Type) EnumDescriptor() ([]byte, []int) {
	return file_protos_v1_entities_wealth_proto_rawDescGZIP(), []int{1, 0}
}

type Worth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Earnings      []*Wealth              `protobuf:"bytes,3,rep,name=earnings,proto3" json:"earnings,omitempty"`
	Expenses      []*Wealth              `protobuf:"bytes,4,rep,name=expenses,proto3" json:"expenses,omitempty"`
	Liabilities   []*Wealth              `protobuf:"bytes,5,rep,name=liabilities,proto3" json:"liabilities,omitempty"`
	Savings       []*Wealth              `protobuf:"bytes,6,rep,name=savings,proto3" json:"savings,omitempty"`
	Investments   []*Wealth              `protobuf:"bytes,7,rep,name=investments,proto3" json:"investments,omitempty"`
	Insurances    []*Wealth              `protobuf:"bytes,8,rep,name=insurances,proto3" json:"insurances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Worth) Reset() {
	*x = Worth{}
	mi := &file_protos_v1_entities_wealth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worth) ProtoMessage() {}

func (x *Worth) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_entities_wealth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worth.ProtoReflect.Descriptor instead.
func (*Worth) Descriptor() ([]byte, []int) {
	return file_protos_v1_entities_wealth_proto_rawDescGZIP(), []int{0}
}

func (x *Worth) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Worth) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Worth) GetEarnings() []*Wealth {
	if x != nil {
		return x.Earnings
	}
	return nil
}

func (x *Worth) GetExpenses() []*Wealth {
	if x != nil {
		return x.Expenses
	}
	return nil
}

func (x *Worth) GetLiabilities() []*Wealth {
	if x != nil {
		return x.Liabilities
	}
	return nil
}

func (x *Worth) GetSavings() []*Wealth {
	if x != nil {
		return x.Savings
	}
	return nil
}

func (x *Worth) GetInvestments() []*Wealth {
	if x != nil {
		return x.Investments
	}
	return nil
}

func (x *Worth) GetInsurances() []*Wealth {
	if x != nil {
		return x.Insurances
	}
	return nil
}

type Wealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          Wealth_Type            `protobuf:"varint,2,opt,name=type,proto3,enum=inflict.v1.entities.Wealth_Type" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Deleted       bool                   `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Value         *Amount                `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Returns       []*Return              `protobuf:"bytes,6,rep,name=returns,proto3" json:"returns,omitempty"`
	Maintainance  []*Maintainance        `protobuf:"bytes,7,rep,name=maintainance,proto3" json:"maintainance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wealth) Reset() {
	*x = Wealth{}
	mi := &file_protos_v1_entities_wealth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wealth) ProtoMessage() {}

func (x *Wealth) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_entities_wealth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wealth.ProtoReflect.Descriptor instead.
func (*Wealth) Descriptor() ([]byte, []int) {
	return file_protos_v1_entities_wealth_proto_rawDescGZIP(), []int{1}
}

func (x *Wealth) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wealth) GetType() Wealth_Type {
	if x != nil {
		return x.Type
	}
	return Wealth_TYPE_UNSPECIFIED
}

func (x *Wealth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Wealth) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Wealth) GetValue() *Amount {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Wealth) GetReturns() []*Return {
	if x != nil {
		return x.Returns
	}
	return nil
}

func (x *Wealth) GetMaintainance() []*Maintainance {
	if x != nil {
		return x.Maintainance
	}
	return nil
}

type Return struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rate           *Rate                  `protobuf:"bytes,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Duration       *durationpb.Duration   `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	MaturityCorpus *Amount                `protobuf:"bytes,5,opt,name=maturity_corpus,json=maturityCorpus,proto3" json:"maturity_corpus,omitempty"`
	Deleted        bool                   `protobuf:"varint,6,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Return) Reset() {
	*x = Return{}
	mi := &file_protos_v1_entities_wealth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Return) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Return) ProtoMessage() {}

func (x *Return) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_entities_wealth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Return.ProtoReflect.Descriptor instead.
func (*Return) Descriptor() ([]byte, []int) {
	return file_protos_v1_entities_wealth_proto_rawDescGZIP(), []int{2}
}

func (x *Return) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Return) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Return) GetRate() *Rate {
	if x != nil {
		return x.Rate
	}
	return nil
}

func (x *Return) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Return) GetMaturityCorpus() *Amount {
	if x != nil {
		return x.MaturityCorpus
	}
	return nil
}

func (x *Return) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_protos_v1_entities_wealth_proto protoreflect.FileDescriptor

const file_protos_v1_entities_wealth_proto_rawDesc = "" +
	"\n" +
	"\x1fprotos/v1/entities/wealth.proto\x12\x13inflict.v1.entities\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fprotos/v1/entities/amount.proto\x1a%protos/v1/entities/maintainance.proto\x1a\x1dprotos/v1/entities/rate.proto\"\x95\x03\n" +
	"\x05Worth\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeleted\x127\n" +
	"\bearnings\x18\x03 \x03(\v2\x1b.inflict.v1.entities.WealthR\bearnings\x127\n" +
	"\bexpenses\x18\x04 \x03(\v2\x1b.inflict.v1.entities.WealthR\bexpenses\x12=\n" +
	"\vliabilities\x18\x05 \x03(\v2\x1b.inflict.v1.entities.WealthR\vliabilities\x125\n" +
	"\asavings\x18\x06 \x03(\v2\x1b.inflict.v1.entities.WealthR\asavings\x12=\n" +
	"\vinvestments\x18\a \x03(\v2\x1b.inflict.v1.entities.WealthR\vinvestments\x12;\n" +
	"\n" +
	"insurances\x18\b \x03(\v2\x1b.inflict.v1.entities.WealthR\n" +
	"insurances\"\xbe\x03\n" +
	"\x06Wealth\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x04type\x18\x02 \x01(\x0e2 .inflict.v1.entities.Wealth.TypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\bR\adeleted\x121\n" +
	"\x05value\x18\x05 \x01(\v2\x1b.inflict.v1.entities.AmountR\x05value\x125\n" +
	"\areturns\x18\x06 \x03(\v2\x1b.inflict.v1.entities.ReturnR\areturns\x12E\n" +
	"\fmaintainance\x18\a \x03(\v2!.inflict.v1.entities.MaintainanceR\fmaintainance\"\x8e\x01\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTYPE_EARNING\x10\x01\x12\x10\n" +
	"\fTYPE_EXPENSE\x10\x02\x12\x12\n" +
	"\x0eTYPE_LIABILITY\x10\x03\x12\x0f\n" +
	"\vTYPE_SAVING\x10\x04\x12\x13\n" +
	"\x0fTYPE_INVESTMENT\x10\x05\x12\x12\n" +
	"\x0eTYPE_INSURANCE\x10\x06\"\xf2\x01\n" +
	"\x06Return\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x04rate\x18\x03 \x01(\v2\x19.inflict.v1.entities.RateR\x04rate\x125\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12D\n" +
	"\x0fmaturity_corpus\x18\x05 \x01(\v2\x1b.inflict.v1.entities.AmountR\x0ematurityCorpus\x12\x18\n" +
	"\adeleted\x18\x06 \x01(\bR\adeletedB\xc2\x01\n" +
	"\x17com.inflict.v1.entitiesB\vWealthProtoP\x01Z,go.ssnk.in/inflict/schema/protos/v1/entities\xa2\x02\x03IVE\xaa\x02\x13Inflict.V1.Entities\xca\x02\x13Inflict\\V1\\Entities\xe2\x02\x1fInflict\\V1\\Entities\\GPBMetadata\xea\x02\x15Inflict::V1::Entitiesb\x06proto3"

var (
	file_protos_v1_entities_wealth_proto_rawDescOnce sync.Once
	file_protos_v1_entities_wealth_proto_rawDescData []byte
)

func file_protos_v1_entities_wealth_proto_rawDescGZIP() []byte {
	file_protos_v1_entities_wealth_proto_rawDescOnce.Do(func() {
		file_protos_v1_entities_wealth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_v1_entities_wealth_proto_rawDesc), len(file_protos_v1_entities_wealth_proto_rawDesc)))
	})
	return file_protos_v1_entities_wealth_proto_rawDescData
}

var file_protos_v1_entities_wealth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_v1_entities_wealth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_v1_entities_wealth_proto_goTypes = []any{
	(Wealth_Type)(0),            // 0: inflict.v1.entities.Wealth.Type
	(*Worth)(nil),               // 1: inflict.v1.entities.Worth
	(*Wealth)(nil),              // 2: inflict.v1.entities.Wealth
	(*Return)(nil),              // 3: inflict.v1.entities.Return
	(*Amount)(nil),              // 4: inflict.v1.entities.Amount
	(*Maintainance)(nil),        // 5: inflict.v1.entities.Maintainance
	(*Rate)(nil),                // 6: inflict.v1.entities.Rate
	(*durationpb.Duration)(nil), // 7: google.protobuf.Duration
}
var file_protos_v1_entities_wealth_proto_depIdxs = []int32{
	2,  // 0: inflict.v1.entities.Worth.earnings:type_name -> inflict.v1.entities.Wealth
	2,  // 1: inflict.v1.entities.Worth.expenses:type_name -> inflict.v1.entities.Wealth
	2,  // 2: inflict.v1.entities.Worth.liabilities:type_name -> inflict.v1.entities.Wealth
	2,  // 3: inflict.v1.entities.Worth.savings:type_name -> inflict.v1.entities.Wealth
	2,  // 4: inflict.v1.entities.Worth.investments:type_name -> inflict.v1.entities.Wealth
	2,  // 5: inflict.v1.entities.Worth.insurances:type_name -> inflict.v1.entities.Wealth
	0,  // 6: inflict.v1.entities.Wealth.type:type_name -> inflict.v1.entities.Wealth.Type
	4,  // 7: inflict.v1.entities.Wealth.value:type_name -> inflict.v1.entities.Amount
	3,  // 8: inflict.v1.entities.Wealth.returns:type_name -> inflict.v1.entities.Return
	5,  // 9: inflict.v1.entities.Wealth.maintainance:type_name -> inflict.v1.entities.Maintainance
	6,  // 10: inflict.v1.entities.Return.rate:type_name -> inflict.v1.entities.Rate
	7,  // 11: inflict.v1.entities.Return.duration:type_name -> google.protobuf.Duration
	4,  // 12: inflict.v1.entities.Return.maturity_corpus:type_name -> inflict.v1.entities.Amount
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_protos_v1_entities_wealth_proto_init() }
func file_protos_v1_entities_wealth_proto_init() {
	if File_protos_v1_entities_wealth_proto != nil {
		return
	}
	file_protos_v1_entities_amount_proto_init()
	file_protos_v1_entities_maintainance_proto_init()
	file_protos_v1_entities_rate_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_v1_entities_wealth_proto_rawDesc), len(file_protos_v1_entities_wealth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_v1_entities_wealth_proto_goTypes,
		DependencyIndexes: file_protos_v1_entities_wealth_proto_depIdxs,
		EnumInfos:         file_protos_v1_entities_wealth_proto_enumTypes,
		MessageInfos:      file_protos_v1_entities_wealth_proto_msgTypes,
	}.Build()
	File_protos_v1_entities_wealth_proto = out.File
	file_protos_v1_entities_wealth_proto_goTypes = nil
	file_protos_v1_entities_wealth_proto_depIdxs = nil
}
