/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter long_type_string,force_optimize_code_size,generate_dependencies,keep_enum_prefix,ts_nocheck,eslint_disable,add_pb_suffix
// @generated from protobuf file "protos/v1/entities/accomodation.proto" (package "inflict.v1.entities", syntax proto3)
// tslint:disable
// @ts-nocheck
import { MessageType } from "@protobuf-ts/runtime";
import { Cost } from "./cost_pb";
/**
 * @generated from protobuf message inflict.v1.entities.Accomodation
 */
export interface Accomodation {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: inflict.v1.entities.Accomodation.Type type = 2
     */
    type: Accomodation_Type;
    /**
     * @generated from protobuf field: inflict.v1.entities.Cost cost = 3
     */
    cost?: Cost;
    /**
     * @generated from protobuf field: string address = 4
     */
    address: string;
}
/**
 * @generated from protobuf enum inflict.v1.entities.Accomodation.Type
 */
export enum Accomodation_Type {
    /**
     * @generated from protobuf enum value: TYPE_UNSPECIFIED = 0;
     */
    TYPE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: TYPE_OWNED = 1;
     */
    TYPE_OWNED = 1,
    /**
     * @generated from protobuf enum value: TYPE_LEASED = 2;
     */
    TYPE_LEASED = 2,
    /**
     * @generated from protobuf enum value: TYPE_RENTED = 3;
     */
    TYPE_RENTED = 3,
    /**
     * @generated from protobuf enum value: TYPE_SHARED = 4;
     */
    TYPE_SHARED = 4
}
// @generated message type with reflection information, may provide speed optimized methods
class Accomodation$Type extends MessageType<Accomodation> {
    constructor() {
        super("inflict.v1.entities.Accomodation", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "enum", T: () => ["inflict.v1.entities.Accomodation.Type", Accomodation_Type] },
            { no: 3, name: "cost", kind: "message", T: () => Cost },
            { no: 4, name: "address", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.entities.Accomodation
 */
export const Accomodation = new Accomodation$Type();
