/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter long_type_string,force_optimize_code_size,generate_dependencies,keep_enum_prefix,ts_nocheck,eslint_disable,add_pb_suffix
// @generated from protobuf file "protos/v1/entities/amount.proto" (package "inflict.v1.entities", syntax proto3)
// tslint:disable
// @ts-nocheck
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Ideate Fixed, Variable, Recurring & OneTime amounts
 *
 * @generated from protobuf message inflict.v1.entities.Amount
 */
export interface Amount {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: inflict.v1.entities.Amount.Type type = 2
     */
    type: Amount_Type;
    /**
     * @generated from protobuf field: string name = 3
     */
    name: string;
    /**
     * @generated from protobuf field: string sender = 4
     */
    sender: string;
    /**
     * @generated from protobuf field: string receiver = 5
     */
    receiver: string;
    /**
     * @generated from protobuf field: int64 value = 6
     */
    value: string;
    /**
     * @generated from protobuf field: string currency = 7
     */
    currency: string;
    /**
     * @generated from protobuf field: bool deleted = 8
     */
    deleted: boolean;
}
/**
 * @generated from protobuf enum inflict.v1.entities.Amount.Type
 */
export enum Amount_Type {
    /**
     * @generated from protobuf enum value: TYPE_UNSPECIFIED = 0;
     */
    TYPE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: TYPE_CREDIT = 1;
     */
    TYPE_CREDIT = 1,
    /**
     * @generated from protobuf enum value: TYPE_DEBIT = 2;
     */
    TYPE_DEBIT = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class Amount$Type extends MessageType<Amount> {
    constructor() {
        super("inflict.v1.entities.Amount", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "enum", T: () => ["inflict.v1.entities.Amount.Type", Amount_Type] },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "sender", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "receiver", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "value", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 7, name: "currency", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "deleted", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.entities.Amount
 */
export const Amount = new Amount$Type();
