/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter long_type_string,force_optimize_code_size,generate_dependencies,keep_enum_prefix,ts_nocheck,eslint_disable,add_pb_suffix
// @generated from protobuf file "protos/v1/entities/common.proto" (package "inflict.v1.entities", syntax proto3)
// tslint:disable
// @ts-nocheck
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Ideate Fixed, Variable, Recurring & OneTime amounts
 *
 * @generated from protobuf message inflict.v1.entities.Amount
 */
export interface Amount {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: inflict.v1.entities.AmountT type = 2
     */
    type: AmountT;
    /**
     * @generated from protobuf field: string name = 3
     */
    name: string;
    /**
     * @generated from protobuf field: string sender = 4
     */
    sender: string;
    /**
     * @generated from protobuf field: string receiver = 5
     */
    receiver: string;
    /**
     * @generated from protobuf field: int64 value = 6
     */
    value: string;
    /**
     * @generated from protobuf field: string currency = 7
     */
    currency: string;
    /**
     * @generated from protobuf field: bool deleted = 8
     */
    deleted: boolean;
}
/**
 * @generated from protobuf message inflict.v1.entities.Rate
 */
export interface Rate {
    /**
     * @generated from protobuf field: inflict.v1.entities.RateT type = 1
     */
    type: RateT;
    /**
     * @generated from protobuf field: int64 value = 2
     */
    value: string;
}
/**
 * @generated from protobuf message inflict.v1.entities.Maintainance
 */
export interface Maintainance {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string type = 2
     */
    type: string;
    /**
     * @generated from protobuf field: inflict.v1.entities.Amount cost = 3
     */
    cost?: Amount;
}
/**
 * @generated from protobuf message inflict.v1.entities.Cost
 */
export interface Cost {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: inflict.v1.entities.Amount amount = 2
     */
    amount?: Amount;
    /**
     * @generated from protobuf field: inflict.v1.entities.Maintainance maintainance = 3
     */
    maintainance?: Maintainance;
}
/**
 * @generated from protobuf message inflict.v1.entities.Accomodation
 */
export interface Accomodation {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: inflict.v1.entities.AccomodationT type = 2
     */
    type: AccomodationT;
    /**
     * @generated from protobuf field: inflict.v1.entities.Cost cost = 3
     */
    cost?: Cost;
    /**
     * @generated from protobuf field: string address = 4
     */
    address: string;
}
/**
 * @generated from protobuf enum inflict.v1.entities.AmountT
 */
export enum AmountT {
    /**
     * @generated from protobuf enum value: Credit = 0;
     */
    Credit = 0,
    /**
     * @generated from protobuf enum value: Debit = 1;
     */
    Debit = 1
}
/**
 * @generated from protobuf enum inflict.v1.entities.RateT
 */
export enum RateT {
    /**
     * @generated from protobuf enum value: BASIS_POINTS = 0;
     */
    BASIS_POINTS = 0,
    /**
     * @generated from protobuf enum value: PERCENTAGE = 1;
     */
    PERCENTAGE = 1
}
/**
 * @generated from protobuf enum inflict.v1.entities.AccomodationT
 */
export enum AccomodationT {
    /**
     * @generated from protobuf enum value: Owned = 0;
     */
    Owned = 0,
    /**
     * @generated from protobuf enum value: Leased = 1;
     */
    Leased = 1,
    /**
     * @generated from protobuf enum value: Rented = 2;
     */
    Rented = 2,
    /**
     * @generated from protobuf enum value: Shared = 3;
     */
    Shared = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class Amount$Type extends MessageType<Amount> {
    constructor() {
        super("inflict.v1.entities.Amount", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "enum", T: () => ["inflict.v1.entities.AmountT", AmountT] },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "sender", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "receiver", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "value", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 7, name: "currency", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "deleted", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.entities.Amount
 */
export const Amount = new Amount$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Rate$Type extends MessageType<Rate> {
    constructor() {
        super("inflict.v1.entities.Rate", [
            { no: 1, name: "type", kind: "enum", T: () => ["inflict.v1.entities.RateT", RateT] },
            { no: 2, name: "value", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.entities.Rate
 */
export const Rate = new Rate$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Maintainance$Type extends MessageType<Maintainance> {
    constructor() {
        super("inflict.v1.entities.Maintainance", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "cost", kind: "message", T: () => Amount }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.entities.Maintainance
 */
export const Maintainance = new Maintainance$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Cost$Type extends MessageType<Cost> {
    constructor() {
        super("inflict.v1.entities.Cost", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "amount", kind: "message", T: () => Amount },
            { no: 3, name: "maintainance", kind: "message", T: () => Maintainance }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.entities.Cost
 */
export const Cost = new Cost$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Accomodation$Type extends MessageType<Accomodation> {
    constructor() {
        super("inflict.v1.entities.Accomodation", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "enum", T: () => ["inflict.v1.entities.AccomodationT", AccomodationT] },
            { no: 3, name: "cost", kind: "message", T: () => Cost },
            { no: 4, name: "address", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.entities.Accomodation
 */
export const Accomodation = new Accomodation$Type();
