/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter long_type_string,force_optimize_code_size,generate_dependencies,keep_enum_prefix,ts_nocheck,eslint_disable,add_pb_suffix
// @generated from protobuf file "protos/v1/entities/cost.proto" (package "inflict.v1.entities", syntax proto3)
// tslint:disable
// @ts-nocheck
import { MessageType } from "@protobuf-ts/runtime";
import { Maintainance } from "./maintainance_pb";
import { Amount } from "./amount_pb";
/**
 * @generated from protobuf message inflict.v1.entities.Cost
 */
export interface Cost {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: inflict.v1.entities.Amount amount = 2
     */
    amount?: Amount;
    /**
     * @generated from protobuf field: inflict.v1.entities.Maintainance maintainance = 3
     */
    maintainance?: Maintainance;
}
// @generated message type with reflection information, may provide speed optimized methods
class Cost$Type extends MessageType<Cost> {
    constructor() {
        super("inflict.v1.entities.Cost", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "amount", kind: "message", T: () => Amount },
            { no: 3, name: "maintainance", kind: "message", T: () => Maintainance }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.entities.Cost
 */
export const Cost = new Cost$Type();
