/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter long_type_string,force_optimize_code_size,generate_dependencies,keep_enum_prefix,ts_nocheck,eslint_disable,add_pb_suffix
// @generated from protobuf file "protos/v1/entities/entity.proto" (package "inflict.v1.entities", syntax proto3)
// tslint:disable
// @ts-nocheck
import { MessageType } from "@protobuf-ts/runtime";
import { Worth } from "./wealth_pb";
import { Family } from "./family_pb";
import { Member } from "./member_pb";
import { Accomodation } from "./common_pb";
/**
 * @generated from protobuf message inflict.v1.entities.Entity
 */
export interface Entity {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: repeated inflict.v1.entities.Accomodation accomodations = 3
     */
    accomodations: Accomodation[];
    /**
     * @generated from protobuf field: repeated inflict.v1.entities.Member members = 4
     */
    members: Member[];
    /**
     * @generated from protobuf field: repeated inflict.v1.entities.Family community = 5
     */
    community: Family[];
    /**
     * @generated from protobuf field: inflict.v1.entities.Worth net_worth = 6
     */
    netWorth?: Worth;
}
// @generated message type with reflection information, may provide speed optimized methods
class Entity$Type extends MessageType<Entity> {
    constructor() {
        super("inflict.v1.entities.Entity", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "accomodations", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Accomodation },
            { no: 4, name: "members", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Member },
            { no: 5, name: "community", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Family },
            { no: 6, name: "net_worth", kind: "message", T: () => Worth }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.entities.Entity
 */
export const Entity = new Entity$Type();
