/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter long_type_string,force_optimize_code_size,generate_dependencies,keep_enum_prefix,ts_nocheck,eslint_disable,add_pb_suffix
// @generated from protobuf file "protos/v1/entities/family.proto" (package "inflict.v1.entities", syntax proto3)
// tslint:disable
// @ts-nocheck
import { MessageType } from "@protobuf-ts/runtime";
import { Worth } from "./wealth_pb";
import { Accomodation } from "./common_pb";
import { Member } from "./member_pb";
/**
 * @generated from protobuf message inflict.v1.entities.Family
 */
export interface Family {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: inflict.v1.entities.FamilyT type = 3
     */
    type: FamilyT;
    /**
     * @generated from protobuf field: repeated inflict.v1.entities.Member members = 4
     */
    members: Member[];
    /**
     * @generated from protobuf field: repeated inflict.v1.entities.Accomodation accomodations = 5
     */
    accomodations: Accomodation[];
    /**
     * @generated from protobuf field: inflict.v1.entities.Worth net_worth = 6
     */
    netWorth?: Worth;
}
/**
 * @generated from protobuf enum inflict.v1.entities.FamilyT
 */
export enum FamilyT {
    /**
     * @generated from protobuf enum value: Nuclear = 0;
     */
    Nuclear = 0,
    /**
     * @generated from protobuf enum value: Joint = 1;
     */
    Joint = 1
}
// @generated message type with reflection information, may provide speed optimized methods
class Family$Type extends MessageType<Family> {
    constructor() {
        super("inflict.v1.entities.Family", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "type", kind: "enum", T: () => ["inflict.v1.entities.FamilyT", FamilyT] },
            { no: 4, name: "members", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Member },
            { no: 5, name: "accomodations", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Accomodation },
            { no: 6, name: "net_worth", kind: "message", T: () => Worth }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.entities.Family
 */
export const Family = new Family$Type();
