/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter long_type_string,force_optimize_code_size,generate_dependencies,keep_enum_prefix,ts_nocheck,eslint_disable,add_pb_suffix
// @generated from protobuf file "protos/v1/entities/maintainance.proto" (package "inflict.v1.entities", syntax proto3)
// tslint:disable
// @ts-nocheck
import { MessageType } from "@protobuf-ts/runtime";
import { Amount } from "./amount_pb";
/**
 * @generated from protobuf message inflict.v1.entities.Maintainance
 */
export interface Maintainance {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string type = 2
     */
    type: string;
    /**
     * @generated from protobuf field: string name = 3
     */
    name: string;
    /**
     * @generated from protobuf field: inflict.v1.entities.Amount cost = 4
     */
    cost?: Amount;
    /**
     * @generated from protobuf field: bool deleted = 5
     */
    deleted: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class Maintainance$Type extends MessageType<Maintainance> {
    constructor() {
        super("inflict.v1.entities.Maintainance", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "cost", kind: "message", T: () => Amount },
            { no: 5, name: "deleted", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.entities.Maintainance
 */
export const Maintainance = new Maintainance$Type();
