/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter long_type_string,force_optimize_code_size,generate_dependencies,keep_enum_prefix,ts_nocheck,eslint_disable,add_pb_suffix
// @generated from protobuf file "protos/v1/entities/member.proto" (package "inflict.v1.entities", syntax proto3)
// tslint:disable
// @ts-nocheck
import { MessageType } from "@protobuf-ts/runtime";
import { Worth } from "./wealth_pb";
import { Accomodation } from "./accomodation_pb";
/**
 * @generated from protobuf message inflict.v1.entities.Member
 */
export interface Member {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: inflict.v1.entities.Member.Type type = 3
     */
    type: Member_Type;
    /**
     * @generated from protobuf field: repeated inflict.v1.entities.Accomodation accomodations = 4
     */
    accomodations: Accomodation[];
    /**
     * @generated from protobuf field: inflict.v1.entities.Worth net_worth = 5
     */
    netWorth?: Worth;
}
/**
 * @generated from protobuf enum inflict.v1.entities.Member.Type
 */
export enum Member_Type {
    /**
     * @generated from protobuf enum value: TYPE_UNSPECIFIED = 0;
     */
    TYPE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: TYPE_EARNER = 1;
     */
    TYPE_EARNER = 1,
    /**
     * @generated from protobuf enum value: TYPE_DEPENDENT = 2;
     */
    TYPE_DEPENDENT = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class Member$Type extends MessageType<Member> {
    constructor() {
        super("inflict.v1.entities.Member", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "type", kind: "enum", T: () => ["inflict.v1.entities.Member.Type", Member_Type] },
            { no: 4, name: "accomodations", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Accomodation },
            { no: 5, name: "net_worth", kind: "message", T: () => Worth }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.entities.Member
 */
export const Member = new Member$Type();
