/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter long_type_string,force_optimize_code_size,generate_dependencies,keep_enum_prefix,ts_nocheck,eslint_disable,add_pb_suffix
// @generated from protobuf file "protos/v1/entities/rate.proto" (package "inflict.v1.entities", syntax proto3)
// tslint:disable
// @ts-nocheck
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message inflict.v1.entities.Rate
 */
export interface Rate {
    /**
     * @generated from protobuf field: inflict.v1.entities.Rate.Type type = 2
     */
    type: Rate_Type;
    /**
     * @generated from protobuf field: int64 value = 3
     */
    value: string;
}
/**
 * @generated from protobuf enum inflict.v1.entities.Rate.Type
 */
export enum Rate_Type {
    /**
     * @generated from protobuf enum value: TYPE_UNSPECIFIED = 0;
     */
    TYPE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: TYPE_BASIS_POINTS = 1;
     */
    TYPE_BASIS_POINTS = 1,
    /**
     * @generated from protobuf enum value: TYPE_PERCENTAGE = 2;
     */
    TYPE_PERCENTAGE = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class Rate$Type extends MessageType<Rate> {
    constructor() {
        super("inflict.v1.entities.Rate", [
            { no: 2, name: "type", kind: "enum", T: () => ["inflict.v1.entities.Rate.Type", Rate_Type] },
            { no: 3, name: "value", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.entities.Rate
 */
export const Rate = new Rate$Type();
