/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter long_type_string,force_optimize_code_size,generate_dependencies,keep_enum_prefix,ts_nocheck,eslint_disable,add_pb_suffix
// @generated from protobuf file "protos/v1/entities/wealth.proto" (package "inflict.v1.entities", syntax proto3)
// tslint:disable
// @ts-nocheck
import { MessageType } from "@protobuf-ts/runtime";
import { Duration } from "../../../google/protobuf/duration_pb";
import { Rate } from "./rate_pb";
import { Maintainance } from "./maintainance_pb";
import { Amount } from "./amount_pb";
/**
 * @generated from protobuf message inflict.v1.entities.Worth
 */
export interface Worth {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: bool deleted = 2
     */
    deleted: boolean;
    /**
     * @generated from protobuf field: repeated inflict.v1.entities.Wealth earnings = 3
     */
    earnings: Wealth[];
    /**
     * @generated from protobuf field: repeated inflict.v1.entities.Wealth expenses = 4
     */
    expenses: Wealth[];
    /**
     * @generated from protobuf field: repeated inflict.v1.entities.Wealth liabilities = 5
     */
    liabilities: Wealth[];
    /**
     * @generated from protobuf field: repeated inflict.v1.entities.Wealth savings = 6
     */
    savings: Wealth[];
    /**
     * @generated from protobuf field: repeated inflict.v1.entities.Wealth investments = 7
     */
    investments: Wealth[];
    /**
     * @generated from protobuf field: repeated inflict.v1.entities.Wealth insurances = 8
     */
    insurances: Wealth[];
}
/**
 * @generated from protobuf message inflict.v1.entities.Wealth
 */
export interface Wealth {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: inflict.v1.entities.Wealth.Type type = 2
     */
    type: Wealth_Type;
    /**
     * @generated from protobuf field: string name = 3
     */
    name: string;
    /**
     * @generated from protobuf field: bool deleted = 4
     */
    deleted: boolean;
    /**
     * @generated from protobuf field: inflict.v1.entities.Amount value = 5
     */
    value?: Amount;
    /**
     * @generated from protobuf field: repeated inflict.v1.entities.Return returns = 6
     */
    returns: Return[];
    /**
     * @generated from protobuf field: repeated inflict.v1.entities.Maintainance maintainance = 7
     */
    maintainance: Maintainance[];
}
/**
 * Redundant because Worth is the primary table for any Entity, Member or Family, Used for development purposes
 *
 * @generated from protobuf enum inflict.v1.entities.Wealth.Type
 */
export enum Wealth_Type {
    /**
     * @generated from protobuf enum value: TYPE_UNSPECIFIED = 0;
     */
    TYPE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: TYPE_EARNING = 1;
     */
    TYPE_EARNING = 1,
    /**
     * @generated from protobuf enum value: TYPE_EXPENSE = 2;
     */
    TYPE_EXPENSE = 2,
    /**
     * @generated from protobuf enum value: TYPE_LIABILITY = 3;
     */
    TYPE_LIABILITY = 3,
    /**
     * @generated from protobuf enum value: TYPE_SAVING = 4;
     */
    TYPE_SAVING = 4,
    /**
     * @generated from protobuf enum value: TYPE_INVESTMENT = 5;
     */
    TYPE_INVESTMENT = 5,
    /**
     * @generated from protobuf enum value: TYPE_INSURANCE = 6;
     */
    TYPE_INSURANCE = 6
}
/**
 * @generated from protobuf message inflict.v1.entities.Return
 */
export interface Return {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: inflict.v1.entities.Rate rate = 3
     */
    rate?: Rate;
    /**
     * @generated from protobuf field: google.protobuf.Duration duration = 4
     */
    duration?: Duration;
    /**
     * @generated from protobuf field: inflict.v1.entities.Amount maturity_corpus = 5
     */
    maturityCorpus?: Amount;
    /**
     * @generated from protobuf field: bool deleted = 6
     */
    deleted: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class Worth$Type extends MessageType<Worth> {
    constructor() {
        super("inflict.v1.entities.Worth", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "deleted", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "earnings", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Wealth },
            { no: 4, name: "expenses", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Wealth },
            { no: 5, name: "liabilities", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Wealth },
            { no: 6, name: "savings", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Wealth },
            { no: 7, name: "investments", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Wealth },
            { no: 8, name: "insurances", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Wealth }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.entities.Worth
 */
export const Worth = new Worth$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Wealth$Type extends MessageType<Wealth> {
    constructor() {
        super("inflict.v1.entities.Wealth", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "enum", T: () => ["inflict.v1.entities.Wealth.Type", Wealth_Type] },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "deleted", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "value", kind: "message", T: () => Amount },
            { no: 6, name: "returns", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Return },
            { no: 7, name: "maintainance", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Maintainance }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.entities.Wealth
 */
export const Wealth = new Wealth$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Return$Type extends MessageType<Return> {
    constructor() {
        super("inflict.v1.entities.Return", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "rate", kind: "message", T: () => Rate },
            { no: 4, name: "duration", kind: "message", T: () => Duration },
            { no: 5, name: "maturity_corpus", kind: "message", T: () => Amount },
            { no: 6, name: "deleted", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.entities.Return
 */
export const Return = new Return$Type();
