syntax = "proto3";

package inflict.v1.api;

import "protos/v1/entities/amount.proto";
import "protos/v1/entities/entity.proto";
import "protos/v1/entities/family.proto";
import "protos/v1/entities/maintainance.proto";
import "protos/v1/entities/member.proto";
import "protos/v1/entities/wealth.proto";

option go_package = "go.ssnk.in/inflict/schema/protos/v1/api;api";

message Request {
  enum Type {
    TYPE_UNSPECIFIED = 0;
    TYPE_AMOUNT = 1;
    TYPE_MAINTAINANCE = 2;
    TYPE_RETURN = 3;
    TYPE_WEALTH = 4;
    TYPE_WORTH = 5;
  }
  Type entity = 1;
  string id = 2;
  oneof payload {
    inflict.v1.entities.Amount amount = 3;
    inflict.v1.entities.Maintainance maintainance = 4;
    inflict.v1.entities.Return return = 5;
    inflict.v1.entities.Wealth wealth = 6;
    inflict.v1.entities.Worth worth = 7;
  }
}

message Response {
  Status status = 1;
  string id = 2;
  oneof payload {
    inflict.v1.entities.Amount amount = 3;
    inflict.v1.entities.Maintainance maintainance = 4;
    inflict.v1.entities.Return return = 5;
    inflict.v1.entities.Wealth wealth = 6;
    inflict.v1.entities.Worth worth = 7;
  }
}

message Status {
  enum Code {
    CODE_UNSPECIFIED = 0;

    CODE_OK = 200;
    CODE_CREATED = 201;
    CODE_NO_CONTENT = 204;
    CODE_MOVED_PERMANENTLY = 301;
    CODE_TEMPORARY_REDIRECT = 307;
    CODE_BAD_REQUEST = 400;
    CODE_UNAUTHORIZED = 401;
    CODE_FORBIDDEN = 403;
    CODE_NOT_FOUND = 404;
    CODE_CONFLICT = 409;
    CODE_TOO_MANY_REQUESTS = 429;
    CODE_CLIENT_CLOSED_REQUEST = 499;
    CODE_INTERNAL_SERVER_ERROR = 500;
    CODE_SERVICE_UNAVAILABLE = 503;
    CODE_GATEWAY_TIMEOUT = 504;
  }
  Code code = 1;
  Error message = 2;
}

message Error {
  string message = 1;
  string description = 2;
}
