/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter long_type_string,force_optimize_code_size,generate_dependencies,keep_enum_prefix,ts_nocheck,eslint_disable,add_pb_suffix
// @generated from protobuf file "protos/v1/api/api.proto" (package "inflict.v1.api", syntax proto3)
// tslint:disable
// @ts-nocheck
import { MessageType } from "@protobuf-ts/runtime";
import { Worth } from "../entities/wealth_pb";
import { Wealth } from "../entities/wealth_pb";
import { Return } from "../entities/wealth_pb";
import { Maintainance } from "../entities/common_pb";
import { Amount } from "../entities/common_pb";
/**
 * @generated from protobuf message inflict.v1.api.Request
 */
export interface Request {
    /**
     * @generated from protobuf field: inflict.v1.api.EntityT entity = 1
     */
    entity: EntityT;
    /**
     * @generated from protobuf oneof: payload
     */
    payload: {
        oneofKind: "id";
        /**
         * @generated from protobuf field: string id = 2
         */
        id: string;
    } | {
        oneofKind: "amount";
        /**
         * @generated from protobuf field: inflict.v1.entities.Amount amount = 3
         */
        amount: Amount;
    } | {
        oneofKind: "maintainance";
        /**
         * @generated from protobuf field: inflict.v1.entities.Maintainance maintainance = 4
         */
        maintainance: Maintainance;
    } | {
        oneofKind: "return";
        /**
         * @generated from protobuf field: inflict.v1.entities.Return return = 5
         */
        return: Return;
    } | {
        oneofKind: "wealth";
        /**
         * @generated from protobuf field: inflict.v1.entities.Wealth wealth = 6
         */
        wealth: Wealth;
    } | {
        oneofKind: "worth";
        /**
         * @generated from protobuf field: inflict.v1.entities.Worth worth = 7
         */
        worth: Worth;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message inflict.v1.api.Response
 */
export interface Response {
    /**
     * @generated from protobuf field: inflict.v1.api.Status status = 1
     */
    status?: Status;
    /**
     * @generated from protobuf oneof: payload
     */
    payload: {
        oneofKind: "id";
        /**
         * @generated from protobuf field: string id = 2
         */
        id: string;
    } | {
        oneofKind: "amount";
        /**
         * @generated from protobuf field: inflict.v1.entities.Amount amount = 3
         */
        amount: Amount;
    } | {
        oneofKind: "maintainance";
        /**
         * @generated from protobuf field: inflict.v1.entities.Maintainance maintainance = 4
         */
        maintainance: Maintainance;
    } | {
        oneofKind: "return";
        /**
         * @generated from protobuf field: inflict.v1.entities.Return return = 5
         */
        return: Return;
    } | {
        oneofKind: "wealth";
        /**
         * @generated from protobuf field: inflict.v1.entities.Wealth wealth = 6
         */
        wealth: Wealth;
    } | {
        oneofKind: "worth";
        /**
         * @generated from protobuf field: inflict.v1.entities.Worth worth = 7
         */
        worth: Worth;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message inflict.v1.api.Status
 */
export interface Status {
    /**
     * @generated from protobuf field: inflict.v1.api.StatusCode code = 1
     */
    code: StatusCode;
    /**
     * @generated from protobuf field: inflict.v1.api.Error message = 2
     */
    message?: Error;
}
/**
 * @generated from protobuf message inflict.v1.api.Error
 */
export interface Error {
    /**
     * @generated from protobuf field: string message = 1
     */
    message: string;
    /**
     * @generated from protobuf field: string description = 2
     */
    description: string;
}
/**
 * @generated from protobuf enum inflict.v1.api.EntityT
 */
export enum EntityT {
    /**
     * @generated from protobuf enum value: ENTITY_AMOUNT = 0;
     */
    ENTITY_AMOUNT = 0,
    /**
     * @generated from protobuf enum value: ENTITY_MAINTAINANCE = 1;
     */
    ENTITY_MAINTAINANCE = 1,
    /**
     * @generated from protobuf enum value: ENTITY_RETURN = 2;
     */
    ENTITY_RETURN = 2,
    /**
     * @generated from protobuf enum value: ENTITY_WEALTH = 3;
     */
    ENTITY_WEALTH = 3,
    /**
     * @generated from protobuf enum value: ENTITY_WORTH = 4;
     */
    ENTITY_WORTH = 4
}
/**
 * @generated from protobuf enum inflict.v1.api.StatusCode
 */
export enum StatusCode {
    /**
     * Default value. In Protobuf, the 0 value is required as the first element.
     * This serves as a safety catch for uninitialized fields.
     *
     * @generated from protobuf enum value: UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: OK = 200;
     */
    OK = 200,
    /**
     * @generated from protobuf enum value: CREATED = 201;
     */
    CREATED = 201,
    /**
     * @generated from protobuf enum value: NO_CONTENT = 204;
     */
    NO_CONTENT = 204,
    /**
     * @generated from protobuf enum value: MOVED_PERMANENTLY = 301;
     */
    MOVED_PERMANENTLY = 301,
    /**
     * @generated from protobuf enum value: TEMPORARY_REDIRECT = 307;
     */
    TEMPORARY_REDIRECT = 307,
    /**
     * @generated from protobuf enum value: BAD_REQUEST = 400;
     */
    BAD_REQUEST = 400,
    /**
     * @generated from protobuf enum value: UNAUTHORIZED = 401;
     */
    UNAUTHORIZED = 401,
    /**
     * @generated from protobuf enum value: FORBIDDEN = 403;
     */
    FORBIDDEN = 403,
    /**
     * @generated from protobuf enum value: NOT_FOUND = 404;
     */
    NOT_FOUND = 404,
    /**
     * @generated from protobuf enum value: CONFLICT = 409;
     */
    CONFLICT = 409,
    /**
     * @generated from protobuf enum value: TOO_MANY_REQUESTS = 429;
     */
    TOO_MANY_REQUESTS = 429,
    /**
     * @generated from protobuf enum value: CLIENT_CLOSED_REQUEST = 499;
     */
    CLIENT_CLOSED_REQUEST = 499,
    /**
     * @generated from protobuf enum value: INTERNAL_SERVER_ERROR = 500;
     */
    INTERNAL_SERVER_ERROR = 500,
    /**
     * @generated from protobuf enum value: SERVICE_UNAVAILABLE = 503;
     */
    SERVICE_UNAVAILABLE = 503,
    /**
     * @generated from protobuf enum value: GATEWAY_TIMEOUT = 504;
     */
    GATEWAY_TIMEOUT = 504
}
// @generated message type with reflection information, may provide speed optimized methods
class Request$Type extends MessageType<Request> {
    constructor() {
        super("inflict.v1.api.Request", [
            { no: 1, name: "entity", kind: "enum", T: () => ["inflict.v1.api.EntityT", EntityT] },
            { no: 2, name: "id", kind: "scalar", oneof: "payload", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "amount", kind: "message", oneof: "payload", T: () => Amount },
            { no: 4, name: "maintainance", kind: "message", oneof: "payload", T: () => Maintainance },
            { no: 5, name: "return", kind: "message", oneof: "payload", T: () => Return },
            { no: 6, name: "wealth", kind: "message", oneof: "payload", T: () => Wealth },
            { no: 7, name: "worth", kind: "message", oneof: "payload", T: () => Worth }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.api.Request
 */
export const Request = new Request$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Response$Type extends MessageType<Response> {
    constructor() {
        super("inflict.v1.api.Response", [
            { no: 1, name: "status", kind: "message", T: () => Status },
            { no: 2, name: "id", kind: "scalar", oneof: "payload", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "amount", kind: "message", oneof: "payload", T: () => Amount },
            { no: 4, name: "maintainance", kind: "message", oneof: "payload", T: () => Maintainance },
            { no: 5, name: "return", kind: "message", oneof: "payload", T: () => Return },
            { no: 6, name: "wealth", kind: "message", oneof: "payload", T: () => Wealth },
            { no: 7, name: "worth", kind: "message", oneof: "payload", T: () => Worth }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.api.Response
 */
export const Response = new Response$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Status$Type extends MessageType<Status> {
    constructor() {
        super("inflict.v1.api.Status", [
            { no: 1, name: "code", kind: "enum", T: () => ["inflict.v1.api.StatusCode", StatusCode] },
            { no: 2, name: "message", kind: "message", T: () => Error }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.api.Status
 */
export const Status = new Status$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Error$Type extends MessageType<Error> {
    constructor() {
        super("inflict.v1.api.Error", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.api.Error
 */
export const Error = new Error$Type();
