/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter long_type_string,force_optimize_code_size,generate_dependencies,keep_enum_prefix,ts_nocheck,eslint_disable,add_pb_suffix
// @generated from protobuf file "protos/v1/api/api.proto" (package "inflict.v1.api", syntax proto3)
// tslint:disable
// @ts-nocheck
import { MessageType } from "@protobuf-ts/runtime";
import { Worth } from "../entities/wealth_pb";
import { Wealth } from "../entities/wealth_pb";
import { Return } from "../entities/wealth_pb";
import { Maintainance } from "../entities/maintainance_pb";
import { Amount } from "../entities/amount_pb";
/**
 * @generated from protobuf message inflict.v1.api.Request
 */
export interface Request {
    /**
     * @generated from protobuf field: inflict.v1.api.Request.Type entity = 1
     */
    entity: Request_Type;
    /**
     * @generated from protobuf field: string id = 2
     */
    id: string;
    /**
     * @generated from protobuf oneof: payload
     */
    payload: {
        oneofKind: "amount";
        /**
         * @generated from protobuf field: inflict.v1.entities.Amount amount = 3
         */
        amount: Amount;
    } | {
        oneofKind: "maintainance";
        /**
         * @generated from protobuf field: inflict.v1.entities.Maintainance maintainance = 4
         */
        maintainance: Maintainance;
    } | {
        oneofKind: "return";
        /**
         * @generated from protobuf field: inflict.v1.entities.Return return = 5
         */
        return: Return;
    } | {
        oneofKind: "wealth";
        /**
         * @generated from protobuf field: inflict.v1.entities.Wealth wealth = 6
         */
        wealth: Wealth;
    } | {
        oneofKind: "worth";
        /**
         * @generated from protobuf field: inflict.v1.entities.Worth worth = 7
         */
        worth: Worth;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf enum inflict.v1.api.Request.Type
 */
export enum Request_Type {
    /**
     * @generated from protobuf enum value: TYPE_UNSPECIFIED = 0;
     */
    TYPE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: TYPE_AMOUNT = 1;
     */
    TYPE_AMOUNT = 1,
    /**
     * @generated from protobuf enum value: TYPE_MAINTAINANCE = 2;
     */
    TYPE_MAINTAINANCE = 2,
    /**
     * @generated from protobuf enum value: TYPE_RETURN = 3;
     */
    TYPE_RETURN = 3,
    /**
     * @generated from protobuf enum value: TYPE_WEALTH = 4;
     */
    TYPE_WEALTH = 4,
    /**
     * @generated from protobuf enum value: TYPE_WORTH = 5;
     */
    TYPE_WORTH = 5
}
/**
 * @generated from protobuf message inflict.v1.api.Response
 */
export interface Response {
    /**
     * @generated from protobuf field: inflict.v1.api.Status status = 1
     */
    status?: Status;
    /**
     * @generated from protobuf field: string id = 2
     */
    id: string;
    /**
     * @generated from protobuf oneof: payload
     */
    payload: {
        oneofKind: "amount";
        /**
         * @generated from protobuf field: inflict.v1.entities.Amount amount = 3
         */
        amount: Amount;
    } | {
        oneofKind: "maintainance";
        /**
         * @generated from protobuf field: inflict.v1.entities.Maintainance maintainance = 4
         */
        maintainance: Maintainance;
    } | {
        oneofKind: "return";
        /**
         * @generated from protobuf field: inflict.v1.entities.Return return = 5
         */
        return: Return;
    } | {
        oneofKind: "wealth";
        /**
         * @generated from protobuf field: inflict.v1.entities.Wealth wealth = 6
         */
        wealth: Wealth;
    } | {
        oneofKind: "worth";
        /**
         * @generated from protobuf field: inflict.v1.entities.Worth worth = 7
         */
        worth: Worth;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message inflict.v1.api.Status
 */
export interface Status {
    /**
     * @generated from protobuf field: inflict.v1.api.Status.Code code = 1
     */
    code: Status_Code;
    /**
     * @generated from protobuf field: inflict.v1.api.Error message = 2
     */
    message?: Error;
}
/**
 * @generated from protobuf enum inflict.v1.api.Status.Code
 */
export enum Status_Code {
    /**
     * @generated from protobuf enum value: CODE_UNSPECIFIED = 0;
     */
    CODE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: CODE_OK = 200;
     */
    CODE_OK = 200,
    /**
     * @generated from protobuf enum value: CODE_CREATED = 201;
     */
    CODE_CREATED = 201,
    /**
     * @generated from protobuf enum value: CODE_NO_CONTENT = 204;
     */
    CODE_NO_CONTENT = 204,
    /**
     * @generated from protobuf enum value: CODE_MOVED_PERMANENTLY = 301;
     */
    CODE_MOVED_PERMANENTLY = 301,
    /**
     * @generated from protobuf enum value: CODE_TEMPORARY_REDIRECT = 307;
     */
    CODE_TEMPORARY_REDIRECT = 307,
    /**
     * @generated from protobuf enum value: CODE_BAD_REQUEST = 400;
     */
    CODE_BAD_REQUEST = 400,
    /**
     * @generated from protobuf enum value: CODE_UNAUTHORIZED = 401;
     */
    CODE_UNAUTHORIZED = 401,
    /**
     * @generated from protobuf enum value: CODE_FORBIDDEN = 403;
     */
    CODE_FORBIDDEN = 403,
    /**
     * @generated from protobuf enum value: CODE_NOT_FOUND = 404;
     */
    CODE_NOT_FOUND = 404,
    /**
     * @generated from protobuf enum value: CODE_CONFLICT = 409;
     */
    CODE_CONFLICT = 409,
    /**
     * @generated from protobuf enum value: CODE_TOO_MANY_REQUESTS = 429;
     */
    CODE_TOO_MANY_REQUESTS = 429,
    /**
     * @generated from protobuf enum value: CODE_CLIENT_CLOSED_REQUEST = 499;
     */
    CODE_CLIENT_CLOSED_REQUEST = 499,
    /**
     * @generated from protobuf enum value: CODE_INTERNAL_SERVER_ERROR = 500;
     */
    CODE_INTERNAL_SERVER_ERROR = 500,
    /**
     * @generated from protobuf enum value: CODE_SERVICE_UNAVAILABLE = 503;
     */
    CODE_SERVICE_UNAVAILABLE = 503,
    /**
     * @generated from protobuf enum value: CODE_GATEWAY_TIMEOUT = 504;
     */
    CODE_GATEWAY_TIMEOUT = 504
}
/**
 * @generated from protobuf message inflict.v1.api.Error
 */
export interface Error {
    /**
     * @generated from protobuf field: string message = 1
     */
    message: string;
    /**
     * @generated from protobuf field: string description = 2
     */
    description: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class Request$Type extends MessageType<Request> {
    constructor() {
        super("inflict.v1.api.Request", [
            { no: 1, name: "entity", kind: "enum", T: () => ["inflict.v1.api.Request.Type", Request_Type] },
            { no: 2, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "amount", kind: "message", oneof: "payload", T: () => Amount },
            { no: 4, name: "maintainance", kind: "message", oneof: "payload", T: () => Maintainance },
            { no: 5, name: "return", kind: "message", oneof: "payload", T: () => Return },
            { no: 6, name: "wealth", kind: "message", oneof: "payload", T: () => Wealth },
            { no: 7, name: "worth", kind: "message", oneof: "payload", T: () => Worth }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.api.Request
 */
export const Request = new Request$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Response$Type extends MessageType<Response> {
    constructor() {
        super("inflict.v1.api.Response", [
            { no: 1, name: "status", kind: "message", T: () => Status },
            { no: 2, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "amount", kind: "message", oneof: "payload", T: () => Amount },
            { no: 4, name: "maintainance", kind: "message", oneof: "payload", T: () => Maintainance },
            { no: 5, name: "return", kind: "message", oneof: "payload", T: () => Return },
            { no: 6, name: "wealth", kind: "message", oneof: "payload", T: () => Wealth },
            { no: 7, name: "worth", kind: "message", oneof: "payload", T: () => Worth }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.api.Response
 */
export const Response = new Response$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Status$Type extends MessageType<Status> {
    constructor() {
        super("inflict.v1.api.Status", [
            { no: 1, name: "code", kind: "enum", T: () => ["inflict.v1.api.Status.Code", Status_Code] },
            { no: 2, name: "message", kind: "message", T: () => Error }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.api.Status
 */
export const Status = new Status$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Error$Type extends MessageType<Error> {
    constructor() {
        super("inflict.v1.api.Error", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message inflict.v1.api.Error
 */
export const Error = new Error$Type();
